export const Deutch: Record<string, string> = {
  documents: "Dokumente",
  document_hub: "Dokumenten Hub",
  type: "Typ",
  name: "Name",
  created_at: "Erstellt am",
  administration: "Verwaltung",
  create: "Erstellen",
  create_file: "Datei erstellen",
  create_folder: "Ordner erstellen",
  create_a_folder: "Erstellen Sie einen Ordner",
  public: "Öffentlich",
  cancel: "Abbrechen",
  placeholder: "Bitte geben Sie den Ordnernamen ein",
  placeholder_file: "Bitte geben Sie den Dateinamen ein",
  edit: "Bearbeiten",
  edit_folder: "Ordner bearbeiten",
  edit_file: "Datei bearbeiten",
  file: "Datei",
  upload_file: "Datei hochladen",
  update: "Aktualisieren",
  save: "Speichern",
  rename: "Umbenennen",
  are_you_sure_you_want_to_delete: "Sind Sie sicher, dass Sie löschen möchten",
  delete: "Löschen",
  a_file: "Einer Datei",
  a_folder: "Ein Ordner",
  add: "Hinzufügen",
  add_file: "Datei hinzufügen",
  navigation_administration_button_text: "Administration",
  navigation_administration_button_text_exit: "Verlassen",
  navigation_theme_toggle_light: "Hell",
  navigation_theme_toggle_dark: "Dunkel",
  navigation_theme_toggle_system: "System",
  navigation_language_toggle_english: "English",
  navigation_language_toggle_german: "Deutsch",
  navigation_language_toggle_french: "Französisch",
  navigation_language_toggle_spanish: "Spanisch",
  navigation_language_toggle_italian: "Italienisch",
  navigation_language_toggle_portuguese: "Portugiesisch",
  navigation_language_toggle_russian: "Russisch",
  navigation_language_toggle_mandarin: "Mandarin",
  navigation_search_placeholder: "Suchen",
  navigation_footer_text: "Powered by",
  navigation_footer_text_product: "Product",
  search_courseCounter_currentCourses: "Aktuell existierende Kurse",
  news_no_posts_found: "Keine Posts gefunden",
  news_comments_button_label: "Kommentare",
  news_comments_input_placeholder: "Geben Sie Ihren Kommentar ein...",
  news_comments_showmore_label: "Mehr anzeigen +",
  news_comments_reply_button_label: "Antworten",
  live_event_futureAndPast_button_text_future: "Zukünftige Events",
  live_event_futureAndPast_button_text_past: "Vergangene Events",
  live_event_filter_button_text: "Filtern",
  live_event_filter_title: "Live Events Filtern",
  live_event_filter_description: "Sie können Ereignisse filtern, indem Sie das Start- und/oder Enddatum eines Ereignisses angeben.",
};
