export const Deutch: Record<string, string> = {
  documents: "Dokumente",
  document_hub: "Dokumenten-Hub",
  type: "Typ",
  name: "Name",
  created_at: "Erstellt am",
  administration: "Verwaltung",
  create: "Erstellen",
  create_file: "Datei erstellen",
  create_folder: "Ordner erstellen",
  create_a_folder: "Erstellen Sie einen Ordner",
  public: "Öffentlich",
  cancel: "Stornieren",
  placeholder: "Bitte geben Sie den Ordnernamen ein",
  placeholder_file: "Bitte geben Sie den Dateinamen ein",
  edit: "Bearbeiten",
  file: "Datei",
  upload_file: "Datei hochladen",
  update: "Aktualisieren",
  save: "Sparen",
  rename: "Umbenennen",
  are_you_sure_you_want_to_delete: "Sind Sie sicher, dass Sie löschen möchten",
  delete: "Löschen",
  a_file: "Eine Datei",
  a_folder: "Ein Ordner",
  add: "Hinzufügen",
};
