export const English: Record<string, string> = {
  documents: "Documents",
  document_hub: "Document Hub",
  type: "Type",
  name: "Name",
  created_at: "Created At",
  administration: "Administration",
  create: "Create",
  create_file: "Create File",
  create_folder: "Create Folder",
  create_a_folder: "Create a Folder",
  public: "Public",
  cancel: "Cancel",
  placeholder: "Please enter folder name",
  placeholder_file: "Please enter file name",
  edit: "Edit",
  file: "File",
  upload_file: "Upload File",
  update: "Update",
  save: "Save",
  rename: "Rename",
  are_you_sure_you_want_to_delete: "Are you sure you want to delete",
  delete: "Delete",
  add: "Add",
  a_file: "a File",
  a_folder: "a Folder",
};
