export const English: Record<string, string> = {
documents: "Documents",
document_hub: "Document Hub",
type: "Type",
name: "Name",
created_at: "Created At",
administration: "Administration",
create: "Create",
create_file: "Create File",
create_folder: "Create Folder",
create_a_folder: "Create a Folder",
public: "Public",
cancel: "Cancel",
placeholder: "Please enter folder name",
placeholder_file: "Please enter file name",
edit: "Edit",
file: "File",
upload_file: "Upload File",
update: "Update",
save: "Save",
rename: "Rename",
are_you_sure_you_want_to_delete: "Are you sure you want to delete",
delete: "Delete",
add: "Add",
a_file: "a File",
a_folder: "a Folder",
navigation_administration_button_text: "Administration",
navigation_administration_button_text_exit: "Exit",
navigation_theme_toggle_light: "Light",
navigation_theme_toggle_dark: "Dark",
navigation_theme_toggle_system: "System",
navigation_language_toggle_english: "English",
navigation_language_toggle_german: "German",
navigation_language_toggle_french: "French",
navigation_language_toggle_spanish: "Spanish",
navigation_language_toggle_italian: "Italian",
navigation_language_toggle_portuguese: "Portuguese",
navigation_language_toggle_russian: "Russian",
navigation_language_toggle_mandarin: "Mandarin",
navigation_search_placeholder: "Search",
navigation_footer_text: "Powered by",
navigation_footer_text_product: "Product",
search_courseCounter_currentCourses: "Current existing Courses",
news_no_posts_found: "No Posts found",
news_comments_button_label: "Comments",
news_comments_input_placeholder: "Type your comment...",
news_comments_showmore_label: "Show More +",
news_comments_reply_button_label: "Reply",
live_event_futureAndPast_button_text_future: "Future Events",
live_event_futureAndPast_button_text_past: "Past Events",
live_event_filter_button_text: "Filter",
live_event_filter_title: "Live Event Filter",
live_event_filter_description: "You can Filter Events by giving  the Start and/or the Enddate of an Event.",
live_event_filter_applyFilter_button_text: "Apply Filter",
live_event_filter_clearFilter_button_text: "Clear Filter",
courses_createCourse_button_text: "New Course",
courses_noCourses_text: "No courses found",
adminTable_previous_button_text: "Previous",
adminTable_next_button_text: "Next",
courses_searchCourses_placeholder: "Filter Courses...",
actions_unpublish: "Unpublish",
actions_publish: "Publish",
courses_titleForm_title: "Course Title",
courses_titleForm_cancel: "Cancel",
courses_titleForm_edit: "Edit Title",
courses_titleForm_placeholder: "e.g. 'Advanced web development'",
courses_titleForm_save: "Save",
courses_descriptionForm_title: "Course Description",
courses_descriptionForm_cancel: "Cancel",
courses_descriptionForm_edit: "Edit Description",
courses_descriptionForm_empty: "No Description",
courses_descriptionForm_placeholder: "e.g. 'This course is about...'",
courses_descriptionForm_save: "Save",
course_imageForm_title: "Course Image",
courses_imageForm_cancel: "Cancel",
courses_imageForm_add: "Add an Image",
courses_imageForm_edit: "Edit Iamge",
courses_imageForm_aspectRatioRecoomendation: "16:9 aspect ratio recommended",
courses_categoryForm_title: "Course Category",
courses_categoryForm_cancel: "Cancel",
courses_categoryForm_edit: "Edit Category",
courses_categoryForm_noCategory: "No Category",
courses_categoryForm_save: "Save",
courses_chaptersForm_title: "Chapter Chapters",
courses_chaptersForm_cancel: "Cancel",
courses_chaptersForm_addChapter: "Add a Chapter",
courses_chaptersForm_placeholder: "e.g. 'Introduction to the course'",
courses_chaptersForm_save: "Create",
courses_chaptersForm_noChapters: "No Chapters",
courses_chaptersForm_reorderInstructions: "Drag and drop to reorder the chapters",
course_priceForm_title: "Course Price",
courses_priceForm_cancel: "Cancel",
courses_priceForm_edit: "Edit Price",
courses_priceForm_noPrice: "No Price",
courses_priceForm_placeholder: "Set a price for your course",
courses_priceForm_save: "Save",
course_attachmentForm_title: "Course Attachments",
course_attachmentForm_cancel: "Cancel",
course_attachmentForm_add: "Add a File",
course_attachmentForm_noAttachments: "No Attachment yet",
course_attachmentForm_Recoomendation: "Add anything your students might need to complete the course.",
confirmModal_DialogHeader: "Are you sure ?",
confirmModal_DialogDescription: "This action cannot be undone.",
confirmModal_DialogConfirm: "Confirm",
confirmModal_DialogCancel: "Cancel",
chapter_TitleForm_title: "Chapter Title",
chapter_TitleForm_cancel: "Cancel",
chapter_TitleForm_edit: "Edit Title",
chapter_TitleForm_save: "Save",
chapter_TitleForm_placeholder: "e.g. 'Introduction to the course'",
chapter_chapterDescriptionForm_title: "Chapter Description",
chapter_chapterDescriptionForm_cancel: "Cancel",
chapter_chapterDescriptionForm_edit: "Edit Description",
chapter_chapterDescriptionForm_noDescription: "No Description",
chapter_chapterDescriptionForm_save: "Save",
chapter_accessForm_title: "Chapter Access",
chapter_accessForm_cancel: "Cancel",
chapter_accessForm_edit: "Edit Access",
chapter_accessForm_isFree: "This chapter is free.",
chapter_accessForm_isNotFree: "This chapter is not free.",
chapter_accessForm_description: "Check this box if you want to make this chapter free.",
chapter_accessForm_save: "Save",
chapter_actions_unpublish: "Unpublish",
chapter_actions_publish: "Publish",
chapter_VideoForm_title: "Chapter Video",
chapter_VideoForm_cancel: "Cancel",
chapter_VideoForm_edit: "Edit Video",
chapter_VideoForm_addVideo: "Add a Video",
chapter_VideoForm_placeholder: "Vimeo share Link",
chapter_VideoForm_urlWarning: "Refresh the page if video does not appear.",
post_createPost_button_text: "Create New Post",
post_noPosts_text: "No Posts found.",
post_search_placeholder_text: "Filter Posts...",
posts_actions_unpublish: "Unpublish",
posts_actions_publish: "Publish",
post_TitleForm_title: "Post Title",
post_TitleForm_cancel: "Cancel",
post_TitleForm_edit: "Edit Title",
post_TitleForm_placeholder: "e.g. 'Advanced web development'",
post_TitleForm_save: "Save",
post_DescriptionForm_title: "Post Description",
post_DescriptionForm_cancel: "Cancel",
post_DescriptionForm_edit: "Edit Description",
post_DescriptionForm_noDescription: "No Description",
post_DescriptionForm_save: "Save",
post_CategoryForm_title: "Post category",
post_CategoryForm_cancel: "Cancel",
post_CategoryForm_edit: "Edit category",
post_CategoryForm_noCategory: "No Category",
post_CategoryForm_save: "Save",
post_ImageForm_title: "Post image",
post_ImageForm_cancel: "Cancel",
post_ImageForm_add: "Add Image",
post_ImageForm_edit: "Edit Image",
post_ImageForm_help: "16:9 aspect ratio recommended",
categories_search_placeholder_text: "Filter categories...",
categories_createCategory_button_text: "New Category",
categories_noCategories_text: "No Results.",
categories_TitleForm_title: "Category Name",
categories_TitleForm_cancel: "Cancel",
categories_TitleForm_edit: "Edit Name",
categories_TitleForm_placeholder: "e.g. 'Advanced web development'",
categories_TitleForm_save: "Save",
category_ColorForm_title: "Category Color",
categories_ColorForm_cancel: "Cancel",
categories_ColorForm_edit: "Edit",
categories_ColorForm_save: "Save",
post_CategoryTypeForm_title: "Category Type",
post_CategoryTypeForm_isCourseCategory: "Course Category",
post_CategoryTypeForm_isNewsCategory: "News Category",
post_CategoryTypeForm_isLiveEventCategory: "Live Event Category",
post_CategoryTypeForm_save: "Save",
customize_ContainerLinkForm_title: "Container Link",
customize_ContainerLinkForm_cancel: "Cancel",
customize_ContainerLinkForm_edit: "Edit Title",
customize_ContainerLinkForm_placeholder: "e.g. 'Advanced web development'",
customize_ContainerLinkForm_save: "Save",
customize_ImageForm_title: "Container Image",
customize_ImageForm_cancel: "Cancel",
customize_ImageForm_addImage: "Add an Image",
customize_ImageForm_edit: "Edit Image",
customize_ImageForm_imageHint: "16:9 aspect ratio recommended",
customize_PrimaryColorForm_cancel: "Cancel",
customize_PrimaryColorForm_edit: "Edit",
customize_PrimaryColorForm_save: "Save",
users_search_placeholder_text: "Filter profiles...",
users_noUsers_text: "No Users.",
user_TitleForm_title: "Username",
user_MailForm_title: "User E-Mail",
user_RoleForm_title: "Profile Role",
user_RoleForm_cancel: "Cancel",
user_RoleForm_edit: "Edit Role",
user_RoleForm_save: "Save",
chat_ChatMessages_loading: "Loading messages...",
chat_ChatMessages_error: "Something went wrong!",
chat_ChatMessages_loadPreviousMessages: "Load previous messages",
chat_ChatItem_viewPDF: "PDF File",
chat_ChatItem_edited: "(edited)",
chat_ChatItem_editMessage: "edited Message",
chat_ChatItem_saveChanges: "Save",
chat_ChatItem_editMessageHint: "Press escape to cancel, enter to save",
chat_ChatInput_placeholder: "Message",
chat_initialModal_title: "Create your Server",
chat_initialModal_description: "Give your server a personality with a name and an image. You can always change it later.",
chat_initialModal_serverName: "Server Name",
chat_initialModal_serverName_placeholder: "Enter Server Name",
chat_initialModal_createServer: "Create",
chat_serverSection_createChannel: "Create Channel",
chat_serverSection_manageMembers: "Manage Members",
chat_server_search_placeholder: "Search",
chat_server_search_notFound: "No Results Found",
chat_server_invite: "Invite People",
chat_server_edit: "Edit Server",
chat_server_manage_members: "Manage Members",
chat_server_create_channel: "Create Channel",
chat_server_delete: "Delete Server",
chat_server_addServer: "Add a Server",
chat_channel_edit: "Edit",
chat_channel_delete: "Delete",
chat_chatItem_edit: "Edit",
chat_chatItem_delete: "Delete",
chat_socket_reconnecting: "Fallback: Polling every 1s",
chat_socket_connected: "Live: Real-time updates",
chat_modal_create_server_title: "Customize your Server",
chat_modal_create_server_description: "Give your server a personality with a name and an image. You can always change it later.",
chat_modal_create_server_name: "Server name",
chat_modal_create_server_name_placeholder: "Enter server name",
chat_modal_create_server_create: "Create",
chat_modal_create_channel_title: "Create Channel",
chat_modal_create_channel_name: "Channel name",
chat_modal_create_channel_name_placeholder: "Enter channel name",
chat_modal_create_channelType_name: "Channel Type",
chat_modal_create_channelType_placeholder: "Select a channel type",
chat_modal_create_channel_create: "Create",
chat_modal_invite_title: "Invite Friends",
chat_modal_invite_link_label: "Server invite link",
chat_modal_invite_new: "Generate a new link",
chat_modal_manageMembers_title: "Manage Members",
chat_modal_manageMembers_description: "Members",
chat_modal_manageMembers_role_label: "Role",
chat_modal_manageMembers_role_guest: "Guest",
chat_modal_manageMembers_role_moderator: "Moderator",
chat_modal_manageMembers_kick: "Kick",
chat_modal_delete_server_title: "Delete Server",
chat_modal_delete_server_description_1: "Are you sure you want to do this?",
chat_modal_delete_server_description_2: "will be permanently deleted.",
chat_modal_delete_server_cancel_button: "Cancel",
chat_modal_delete_server_delete_button: "Confirm",
chat_modal_edit_channel_title: "Edit Channel",
chat_modal_edit_channel_name: "Channel Name",
chat_modal_edit_channel_name_placeholder: "Enter channel name",
chat_modal_edit_channel_type: "Channel Type",
chat_modal_edit_channel_save: "Save",
chat_modal_edit_channel_type_placeholder: "Select a channel type",
chat_modal_deleteChannel_title: "Delete Channel",
chat_modal_deleteChannel_description_1: "Are you sure you want to do this?",
chat_modal_deleteChannel_description_2: "will be permanently deleted.",
chat_modal_deleteChannel_cancel_button: "Cancel",
chat_modal_deleteChannel_delete_button: "Confirm",
chat_modal_leaveServer_title: "Leave Server",
chat_modal_leaveServer_description_1: "Are you sure you want to leave",
chat_modal_leaveServer_cancel: "Cancel",
chat_modal_leaveServer_leave: "Confirm",
chat_modal_messageFile_title: "Add an attachment",
chat_modal_messageFile_description: "Send a file as a message",
chat_modal_messageFile_submit: "Send",
createCourse_title: "Name your Course",
createCourse_description: "What would you like to name your course? Don't worry, you can change this later.",
createCourse_form_label: "Course title",
createCourse_form_description: "What will you teach in this course?",
createCourse_form_placeholder: "e.g. 'Advanced web development'",
createCourse_cancel: "Cancel",
createCourse_submit: "Continue",
createPost_title: "Name your Post",
createPost_description: "What would you like to name your Post? Don't worry, you can change this later.",
createPost_form_label: "Post title",
createPost_form_placeholder: "e.g. 'Advanced web development'",
createPost_form_description: "What will you want to let you know your Community?",
createPost_cancel: "Cancel",
createPost_submit: "Continue",
createLiveEvent_title: "Name your Live Event",
createLiveEvent_description: "What would you like to name your Live Event? Don't worry, you can change this later.",
createLiveEvent_form_label: "Event title",
createLiveEvent_form_placeholder: "e.g. 'Advanced web development'",
createLiveEvent_form_description: "What will you show on your Event?",
createLiveEvent_cancel: "Cancel",
createLiveEvent_submit: "Continue",
createCategory_title: "Name your Category",
createCategory_description: "What would you like to name your Category? Don’t worry, you can change this later.",
createCategory_form_label: "Category Name",
createCategory_form_placeholder: "e.g. 'Advanced web development'",
createCategory_form_description: "What will you categorize on your platform?",
createCategory_cancel: "Cancel",
createCategory_submit: "Save",
liveEvent_createEvent_button_text: "New Live Event",
liveEvent_noEvent_text: "No Events found.",
liveEvent_filterEvents_placeholder: "Filter Events...",
infocard_courses: "Courses",
infocard_course: "Course",
infocard_inprogress: "In Progress",
infocard_completed: "Completed",
no_courses: "No Courses found",
customize_customizeCcontainer_title: "Customize your Container",
customize_customizeCcontainer_requiredFields: "Complete all required fields",
customize_customizeYourCcontainer: "Customize your Container",
requiredFields: "*required",
customize_AddImageTitle: "Add an Image as an Logo",
chat_welcome_title: "Welcome to #",
chat_welcome_description: "This is the start of the #",
chat_welcome_description2: "channel",
chat_welcome_title_directMessage: "This is the start of your conversation with",
serverSidebar_textChannel: "Text Channels",
serverSidebar_videoChannel: "Video Channels",
serverSidebar_audioChannel: "Audio Channels",
serverSidebar_member: "Members",
chat_serversection_label_text: "Text Channels",
chat_serversection_label_audio: "Audio Channels",
chat_serversection_label_video: "Video Channels",
chat_serversection_label_member: "Members",
chat_server_search_command_placeholder: "Search all channels and members",
course_setup_title: "Course Setup",
course_setup_undertitle: "Complete all required fields",
course_setup_course_information_title: "Customize your course",
course_setup_price_title: "Sell your Course",
course_setup_chapters_title: "Course Chapters",
course_setup_attachments_title: "Resources & Attachments",
courses_chapter_backToCourse_button_text: "Back to Course Setup",
courses_chapter_title: "Chapter Creation",
courses_chapter_undertitle: "Complete all fields",
course_chapter_customize_title: "Customize your Chapter",
course_chapter_access: "Access Settings",
course_chapter_video: "Add a Video",
courses_setup_free_badge: "Free",
courses_setup_published_text: "Published",
courses_setup_draft_text: "Draft",
post_setup_title: "Post Setup",
post_setup_undertitle: "Complete all required fields",
post_setup_customize_title: "Customize your Post",
post_setup_image_title: "Add an Image to your Post",
liveEvent_PremiumFeature_description: "To use Live-Events and set up your digital and hybrid Events with our software, you need to use the community package.",
liveEvent_PremiumFeature_button_text: "Buy Community Package",
liveEvent_setup_title: "Event Setup",
liveEvent_setup_undertitle: "Complete all required fields",
liveEvent_setup_customize_title: "Customize your Live Event",
liveEvent_setup_video_title: "Add the Resources to your Event",
category_setup_title: "Category Setup",
category_setup_undertitle: "Complete all required fields",
category_setup_customize_title: "Name your Category",
user_setup_title: "User Setup",
user_setup_undertitle: "Complete all required fields",
user_setup_customize_title: "Customize the User",
course_unpublish_banner: "This course is unpublished. It will not be visible to the Users.",
post_unpublish_banner: "This post is unpublished. It will not be visible to the Users.",
liveEvent_unpublish_banner: "This event is unpublished. It will not be visible to the Users.",
category_unpublish_banner: "This category is unpublished. It will not be visible to the Users.",
chapter_unpublish_banner: "This chapter is unpublished. It will not be visible to the Users.",
analytics_total_revenue_label: "Total Revenue",
analytics_total_sales_label: "Total Sales",
customize_NavColors_title: "Customize your Navigation Colors",
customize_navBackgroundColorForm_title: "Navigation Background Color",
customize_navDarkBackgroundColorForm_title: "Navigation Background Color Darkmode",
customize_navPrimaryColorForm_title: "Navigation Primary Color",
customize_navDarkPrimaryColorForm_title: "Navigation Primary Color Darkmode",
customize_customizeNavigation_title: "Customize your Navigation Colors",
customize_NavColorsDark_title: "Customize your Navigation Colors Darkmode",
settings_menu_containersettings_title: "Container Settings",
settings_menu_navigationdesign_title: "Navigation Design",
settings_backToMenu_button_text: "Back to Menu",
};
