export const English: Record<string, string> = {
  documents: "Documents",
  document_hub: "Document Hub",
  type: "Type",
  name: "Name",
  created_at: "Created At",
  administration: "Administration",
  create: "Create",
  create_file: "Create File",
  create_folder: "Create Folder",
  create_a_folder: "Create a Folder",
  public: "Public",
  cancel: "Cancel",
  placeholder: "Please enter folder name",
  placeholder_file: "Please enter file name",
  edit: "Edit",
  file: "File",
  upload_file: "Upload File",
  update: "Update",
  save: "Save",
  rename: "Rename",
  are_you_sure_you_want_to_delete: "Are you sure you want to delete",
  delete: "Delete",
  add: "Add",
  a_file: "a File",
  a_folder: "a Folder",
  navigation_administration_button_text: "Administration",
  navigation_administration_button_text_exit: "Exit",
  navigation_theme_toggle_light: "Light",
  navigation_theme_toggle_dark: "Dark",
  navigation_theme_toggle_system: "System",
  navigation_language_toggle_english: "English",
  navigation_language_toggle_german: "German",
  navigation_language_toggle_french: "French",
  navigation_language_toggle_spanish: "Spanish",
  navigation_language_toggle_italian: "Italian",
  navigation_language_toggle_portuguese: "Portuguese",
  navigation_language_toggle_russian: "Russian",
  navigation_language_toggle_mandarin: "Mandarin",
  navigation_search_placeholder: "Search",
  navigation_footer_text: "Powered by",
  navigation_footer_text_product: "Product",
  search_courseCounter_currentCourses: "Current existing Courses",
  news_no_posts_found: "No Posts found",
  news_comments_button_label: "Comments",
  news_comments_input_placeholder: "Type your comment...",
  news_comments_showmore_label: "Show More +",
  news_comments_reply_button_label: "Reply",
  live_event_futureAndPast_button_text_future: "Future Events",
  live_event_futureAndPast_button_text_past: "Past Events",
  live_event_filter_button_text: "Filter",
  live_event_filter_title: "Live Event Filter",
  live_event_filter_description: "You can Filter Events by giving  the Start and/or the Enddate of an Event.",
};
