export const Espanol: Record<string, string> = {
  documents: "documentos",
  document_hub: "centro de documentos",
  type: "tipo",
  name: "nombre",
  created_at: "creado en",
  administration: "administración",
  create: "crear",
  create_file: "crear archivo",
  create_folder: "crear carpeta",
  create_a_folder: "crear una carpeta",
  public: "público",
  cancel: "cancelar",
  placeholder: "Por favor, introduzca el nombre de la carpeta",
  placeholder_file: "Por favor, introduzca el nombre del archivo",
  edit: "editar",
  file: "archivo",
  upload_file: "subir archivo",
  update: "actualizar",
  save: "guardar",
  rename: "renombrar",
  are_you_sure_you_want_to_delete: "¿Estás seguro de que quieres eliminar?",
  delete: "eliminar",
  a_file: "a archivo",
  a_folder: "a carpeta",
  add: "agregar",
  navigation_administration_button_text: "Administración",
  navigation_administration_button_text_exit: "Salir",
  navigation_theme_toggle_light: "Luz",
  navigation_theme_toggle_dark: "Oscuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "inglés",
  navigation_language_toggle_german: "alemán",
  navigation_language_toggle_french: "francés",
  navigation_language_toggle_spanish: "español",
  navigation_language_toggle_italian: "italiano",
  navigation_language_toggle_portuguese: "portugués",
  navigation_language_toggle_russian: "ruso",
  navigation_language_toggle_mandarin: "mandarín",
  navigation_search_placeholder: "Buscar",
  navigation_footer_text: "Desarrollado por",
  navigation_footer_text_product: "Producto",
  search_courseCounter_currentCourses: "Cursos existentes actualmente",
  news_no_posts_found: "No se encontraron publicaciones",
  news_comments_button_label: "Comentarios",
  news_comments_input_placeholder: "Escribe tu comentario...",
  news_comments_showmore_label: "Mostrar más +",
  news_comments_reply_button_label: "Responder",
  live_event_futureAndPast_button_text_future: "Eventos futuros",
  live_event_futureAndPast_button_text_past: "Eventos pasados",
  live_event_filter_button_text: "Filtrar",
  live_event_filter_title: "Filtro de eventos en vivo",
  live_event_filter_description: "Puedes filtrar eventos dando la fecha de inicio y/o finalización de un evento.",
  live_event_filter_applyFilter_button_text: "Aplicar filtro",
  live_event_filter_clearFilter_button_text: "Borrar filtro",
  courses_createCourse_button_text: "Nuevo Curso",
courses_noCourses_text: "No se encontraron cursos",
adminTable_previous_button_text: "Anterior",
adminTable_next_button_text: "Siguiente",
courses_searchCourses_placeholder: "Filtrar Cursos...",
actions_unpublish: "Despublicar",
actions_publish: "Publicar",
courses_titleForm_title: "Título del Curso",
courses_titleForm_cancel: "Cancelar",
courses_titleForm_edit: "Editar Título",
courses_titleForm_placeholder: "p.ej. 'Desarrollo web avanzado'",
courses_titleForm_save: "Guardar",
courses_descriptionForm_title: "Descripción del Curso",
courses_descriptionForm_cancel: "Cancelar",
courses_descriptionForm_edit: "Editar Descripción",
courses_descriptionForm_empty: "Sin Descripción",
courses_descriptionForm_placeholder: "p.ej. 'Este curso trata sobre...'",
courses_descriptionForm_save: "Guardar",
course_imageForm_title: "Imagen del Curso",
courses_imageForm_cancel: "Cancelar",
courses_imageForm_add: "Agregar una Imagen",
courses_imageForm_edit: "Editar Imagen",
courses_imageForm_aspectRatioRecoomendation: "Se recomienda una proporción de aspecto de 16:9",
courses_categoryForm_title: "Categoría del Curso",
courses_categoryForm_cancel: "Cancelar",
courses_categoryForm_edit: "Editar Categoría",
courses_categoryForm_noCategory: "Sin Categoría",
courses_categoryForm_save: "Guardar",
courses_chaptersForm_title: "Capítulos del Curso",
courses_chaptersForm_cancel: "Cancelar",
courses_chaptersForm_addChapter: "Agregar un Capítulo",
courses_chaptersForm_placeholder: "p.ej. 'Introducción al curso'",
courses_chaptersForm_save: "Crear",
courses_chaptersForm_noChapters: "Sin Capítulos",
courses_chaptersForm_reorderInstructions: "Arrastrar y soltar para reordenar los capítulos",
course_priceForm_title: "Precio del Curso",
courses_priceForm_cancel: "Cancelar",
courses_priceForm_edit: "Editar Precio",
courses_priceForm_noPrice: "Sin Precio",
courses_priceForm_placeholder: "Establecer un precio para tu curso",
courses_priceForm_save: "Guardar",
course_attachmentForm_title: "Adjuntos del Curso",
course_attachmentForm_cancel: "Cancelar",
course_attachmentForm_add: "Agregar un Archivo",
course_attachmentForm_noAttachments: "Sin Adjuntos aún",
course_attachmentForm_Recoomendation: "Agregar cualquier cosa que tus estudiantes puedan necesitar para completar el curso.",
confirmModal_DialogHeader: "¿Estás seguro?",
confirmModal_DialogDescription: "Esta acción no se puede deshacer.",
confirmModal_DialogConfirm: "Confirmar",
confirmModal_DialogCancel: "Cancelar",
chapter_TitleForm_title: "Título del Capítulo",
chapter_TitleForm_cancel: "Cancelar",
chapter_TitleForm_edit: "Editar Título",
chapter_TitleForm_save: "Guardar",
chapter_TitleForm_placeholder: "p.ej. 'Introducción al curso'",
chapter_chapterDescriptionForm_title: "Descripción del Capítulo",
chapter_chapterDescriptionForm_cancel: "Cancelar",
chapter_chapterDescriptionForm_edit: "Editar Descripción",
chapter_chapterDescriptionForm_noDescription: "Sin Descripción",
chapter_chapterDescriptionForm_save: "Guardar",
chapter_accessForm_title: "Acceso al Capítulo",
chapter_accessForm_cancel: "Cancelar",
chapter_accessForm_edit: "Editar Acceso",
chapter_accessForm_isFree: "Este capítulo es gratuito.",
chapter_accessForm_isNotFree: "Este capítulo no es gratuito.",
chapter_accessForm_description: "Marca esta casilla si quieres que este capítulo sea gratuito.",
chapter_accessForm_save: "Guardar",
chapter_actions_unpublish: "Despublicar",
chapter_actions_publish: "Publicar",
chapter_VideoForm_title: "Video del Capítulo",
chapter_VideoForm_cancel: "Cancelar",
chapter_VideoForm_edit: "Editar Video",
chapter_VideoForm_addVideo: "Agregar un Video",
chapter_VideoForm_placeholder: "Enlace de compartición de Vimeo",
chapter_VideoForm_urlWarning: "Actualizar la página si el video no aparece.",
post_createPost_button_text: "Nueva Publicación",
post_noPosts_text: "No se encontraron publicaciones.",
post_search_placeholder_text: "Filtrar Publicaciones...",
posts_actions_unpublish: "Despublicar",
posts_actions_publish: "Publicar",
post_TitleForm_title: "Título de la Publicación",
post_TitleForm_cancel: "Cancelar",
post_TitleForm_edit: "Editar Título",
post_TitleForm_placeholder: "p.ej. 'Desarrollo web avanzado'",
post_TitleForm_save: "Guardar",
post_DescriptionForm_title: "Descripción de la Publicación",
post_DescriptionForm_cancel: "Cancelar",
post_DescriptionForm_edit: "Editar Descripción",
post_DescriptionForm_noDescription: "Sin Descripción",
post_DescriptionForm_save: "Guardar",
post_CategoryForm_title: "Categoría de la Publicación",
post_CategoryForm_cancel: "Cancelar",
post_CategoryForm_edit: "Editar Categoría",
post_CategoryForm_noCategory: "Sin Categoría",
post_CategoryForm_save: "Guardar",
post_ImageForm_title: "Imagen de la Publicación",
post_ImageForm_cancel: "Cancelar",
post_ImageForm_add: "Añadir Imagen",
post_ImageForm_edit: "Editar Imagen",
post_ImageForm_help: "Se recomienda una relación de aspecto de 16:9",
categories_search_placeholder_text: "Filtrar Categorías...",
categories_createCategory_button_text: "Nueva Categoría",
categories_noCategories_text: "Sin Resultados.",
categories_TitleForm_title: "Nombre de la Categoría",
categories_TitleForm_cancel: "Cancelar",
categories_TitleForm_edit: "Editar Nombre",
categories_TitleForm_placeholder: "p. ej., 'Desarrollo web avanzado'",
categories_TitleForm_save: "Guardar",
category_ColorForm_title: "Color de la Categoría",
categories_ColorForm_cancel: "Cancelar",
categories_ColorForm_edit: "Editar",
categories_ColorForm_save: "Guardar",
post_CategoryTypeForm_title: "Tipo de Categoría",
post_CategoryTypeForm_isCourseCategory: "Categoría de Curso",
post_CategoryTypeForm_isNewsCategory: "Categoría de Noticias",
post_CategoryTypeForm_isLiveEventCategory: "Categoría de Evento en Vivo",
post_CategoryTypeForm_save: "Guardar",
customize_ContainerLinkForm_title: "Enlace del Contenedor",
customize_ContainerLinkForm_cancel: "Cancelar",
customize_ContainerLinkForm_edit: "Editar Título",
customize_ContainerLinkForm_placeholder: "p. ej., 'Desarrollo web avanzado'",
customize_ContainerLinkForm_save: "Guardar",
customize_ImageForm_title: "Imagen del Contenedor",
customize_ImageForm_cancel: "Cancelar",
customize_ImageForm_addImage: "Añadir una Imagen",
customize_ImageForm_edit: "Editar Imagen",
customize_ImageForm_imageHint: "Se recomienda una relación de aspecto de 16:9",
customize_PrimaryColorForm_title: "Color Primario",
customize_PrimaryColorForm_cancel: "Cancelar",
customize_PrimaryColorForm_edit: "Editar",
customize_PrimaryColorForm_save: "Guardar",
users_search_placeholder_text: "Filtrar Perfiles...",
users_noUsers_text: "Sin Usuarios.",
user_TitleForm_title: "Nombre de Usuario",
user_MailForm_title: "Correo Electrónico del Usuario",
user_RoleForm_title: "Rol del Perfil",
user_RoleForm_cancel: "Cancelar",
user_RoleForm_edit: "Editar Rol",
user_RoleForm_save: "Guardar",
chat_ChatMessages_loading: "Cargando mensajes...",
chat_ChatMessages_error: "¡Algo salió mal!",
chat_ChatMessages_loadPreviousMessages: "Cargar mensajes anteriores",
chat_ChatItem_viewPDF: "Archivo PDF",
chat_ChatItem_edited: "(editado)",
chat_ChatItem_editMessage: "editar Mensaje",
chat_ChatItem_saveChanges: "Guardar",
chat_ChatItem_editMessageHint: "Presiona escape para cancelar, enter para guardar",
chat_ChatInput_placeholder: "Mensaje",
chat_initialModal_title: "Crear tu Servidor",
chat_initialModal_description: "Dale personalidad a tu servidor con un nombre y una imagen. Siempre puedes cambiarlo más tarde.",
chat_initialModal_serverName: "Nombre del Servidor",
chat_initialModal_serverName_placeholder: "Introduce el Nombre del Servidor",
chat_initialModal_createServer: "Crear",
chat_serverSection_createChannel: "Crear Canal",
chat_serverSection_manageMembers: "Gestionar Miembros",
chat_server_search_placeholder: "Buscar",
chat_server_search_notFound: "Sin Resultados",
chat_server_invite: "Invitar a Gente",
chat_server_edit: "Editar Servidor",
chat_server_manage_members: "Gestionar Miembros",
chat_server_create_channel: "Crear Canal",
chat_server_delete: "Eliminar Servidor",
chat_server_addServer: "Añadir un Servidor",
chat_channel_edit: "Editar",
chat_channel_delete: "Eliminar",
chat_chatItem_edit: "Editar",
chat_chatItem_delete: "Eliminar",
chat_socket_reconnecting: "Conexión de respaldo: Sondeo cada 1s",
chat_socket_connected: "En vivo: Actualizaciones en tiempo real",
chat_modal_create_server_title: "Personalizar tu Servidor",
chat_modal_create_server_description: "Dale personalidad a tu servidor con un nombre y una imagen. Siempre puedes cambiarlo más tarde.",
chat_modal_create_server_name: "Nombre del servidor",
chat_modal_create_server_name_placeholder: "Ingresa el nombre del servidor",
chat_modal_create_server_create: "Crear",
chat_modal_create_channel_title: "Crear canal",
chat_modal_create_channel_name: "Nombre del canal",
chat_modal_create_channel_name_placeholder: "Ingresa el nombre del canal",
chat_modal_create_channelType_name: "Tipo de canal",
chat_modal_create_channelType_placeholder: "Selecciona un tipo de canal",
chat_modal_create_channel_create: "Crear",
chat_modal_invite_title: "Invitar amigos",
chat_modal_invite_link_label: "Enlace de invitación al servidor",
chat_modal_invite_new: "Generar un nuevo enlace",
chat_modal_manageMembers_title: "Gestionar miembros",
chat_modal_manageMembers_description: "Miembros",
chat_modal_manageMembers_role_label: "Rol",
chat_modal_manageMembers_role_guest: "Invitado",
chat_modal_manageMembers_role_moderator: "Moderador",
chat_modal_manageMembers_kick: "Expulsar",
chat_modal_delete_server_title: "Eliminar servidor",
chat_modal_delete_server_description_1: "¿Estás seguro de que quieres hacer esto?",
chat_modal_delete_server_description_2: "será eliminado permanentemente.",
chat_modal_delete_server_cancel_button: "Cancelar",
chat_modal_delete_server_delete_button: "Confirmar",
chat_modal_edit_channel_title: "Editar canal",
chat_modal_edit_channel_name: "Nombre del canal",
chat_modal_edit_channel_name_placeholder: "Ingresa el nombre del canal",
chat_modal_edit_channel_type: "Tipo de canal",
chat_modal_edit_channel_save: "Guardar",
chat_modal_edit_channel_type_placeholder: "Selecciona un tipo de canal",
chat_modal_deleteChannel_title: "Eliminar canal",
chat_modal_deleteChannel_description_1: "¿Estás seguro de que quieres hacer esto?",
chat_modal_deleteChannel_description_2: "será eliminado permanentemente.",
chat_modal_deleteChannel_cancel_button: "Cancelar",
chat_modal_deleteChannel_delete_button: "Confirmar",
chat_modal_leaveServer_title: "Dejar el servidor",
chat_modal_leaveServer_description_1: "¿Estás seguro de que quieres salir",
chat_modal_leaveServer_cancel: "Cancelar",
chat_modal_leaveServer_leave: "Confirmar",
chat_modal_messageFile_title: "Añadir un adjunto",
chat_modal_messageFile_description: "Enviar un archivo como mensaje",
chat_modal_messageFile_submit: "Enviar",
createCourse_title: "Nombrar tu curso",
createCourse_description: "¿Cómo te gustaría nombrar tu curso? No te preocupes, puedes cambiarlo más tarde.",
createCourse_form_label: "Título del curso",
createCourse_form_description: "¿Qué enseñarás en este curso?",
createCourse_form_placeholder: "p. ej., 'Desarrollo web avanzado'",
createCourse_cancel: "Cancelar",
createCourse_submit: "Continuar",
createPost_title: "Nombrar tu publicación",
createPost_description: "¿Cómo te gustaría nombrar tu publicación? No te preocupes, puedes cambiarlo más tarde.",
createPost_form_label: "Título de la publicación",
createPost_form_placeholder: "p. ej., 'Desarrollo web avanzado'",
createPost_form_description: "¿Qué quieres que sepa tu comunidad?",
createPost_cancel: "Cancelar",
createPost_submit: "Continuar",
createLiveEvent_title: "Nombrar tu evento en vivo",
createLiveEvent_description: "¿Cómo te gustaría nombrar tu evento en vivo? No te preocupes, puedes cambiarlo más tarde.",
createLiveEvent_form_label: "Título del evento",
createLiveEvent_form_placeholder: "p. ej., 'Desarrollo web avanzado'",
createLiveEvent_form_description: "¿Qué mostrarás en tu evento?",
createLiveEvent_cancel: "Cancelar",
createLiveEvent_submit: "Continuar",
createCategory_title: "Nombrar tu categoría",
createCategory_description: "¿Cómo te gustaría nombrar tu categoría? No te preocupes, puedes cambiarlo más tarde.",
createCategory_form_label: "Nombre de la categoría",
createCategory_form_placeholder: "p. ej., 'Desarrollo web avanzado'",
createCategory_form_description: "¿Qué categorizarás en tu plataforma?",
createCategory_cancel: "Cancelar",
createCategory_submit: "Guardar",
liveEvent_createEvent_button_text: "Nuevo Evento",
liveEvent_noEvent_text: "No se encontraron eventos.",
liveEvent_filterEvents_placeholder: "Filtrar Eventos...",
infocard_courses: "Cursos",
infocard_course: "Curso",
infocard_inprogress: "En Progreso",
infocard_completed: "Completado",
no_courses: "No se encontraron cursos",
customize_customizeCcontainer_title: "Personaliza tu Contenedor",
customize_customizeCcontainer_requiredFields: "Completa todos los campos obligatorios",
customize_customizeYourCcontainer: "Personaliza tu Contenedor",
requiredFields: "*obligatorio",
customize_AddImageTitle: "Añade una Imagen como Logotipo",
chat_welcome_title: "Bienvenido a #",
chat_welcome_description: "Este es el inicio del canal #",
chat_welcome_description2: "canal",
chat_welcome_title_directMessage: "Este es el inicio de tu conversación con",
serverSidebar_textChannel: "Canales de Texto",
serverSidebar_videoChannel: "Canales de Video",
serverSidebar_audioChannel: "Canales de Audio",
serverSidebar_member: "Miembros",
chat_serversection_label_text: "Canales de Texto",
chat_serversection_label_audio: "Canales de Audio",
chat_serversection_label_video: "Canales de Video",
chat_serversection_label_member: "Miembros",
chat_server_search_command_placeholder: "Buscar en todos los canales y miembros",
course_setup_title: "Configuración del Curso",
course_setup_undertitle: "Completa todos los campos obligatorios",
course_setup_course_information_title: "Personaliza tu curso",
course_setup_price_title: "Vende tu Curso",
course_setup_chapters_title: "Capítulos del Curso",
course_setup_attachments_title: "Recursos & Adjuntos",
courses_chapter_backToCourse_button_text: "Volver a la Configuración del Curso",
courses_chapter_title: "Creación de Capítulo",
courses_chapter_undertitle: "Completa todos los campos",
course_chapter_customize_title: "Personaliza tu Capítulo",
course_chapter_access: "Configuración de Acceso",
course_chapter_video: "Añadir un Video",
courses_setup_free_badge: "Gratis",
courses_setup_published_text: "Publicado",
courses_setup_draft_text: "Borrador",
post_setup_title: "Configuración de Publicación",
post_setup_undertitle: "Completa todos los campos obligatorios",
post_setup_customize_title: "Personaliza tu Publicación",
post_setup_image_title: "Añade una Imagen a tu Publicación",
liveEvent_PremiumFeature_description: "Para usar Eventos en Vivo y configurar tus eventos digitales y híbridos con nuestro software, necesitas usar el paquete comunitario.",
liveEvent_PremiumFeature_button_text: "Comprar Paquete Comunitario",
liveEvent_setup_title: "Configuración de Evento en Vivo",
liveEvent_setup_undertitle: "Completa todos los campos obligatorios",
liveEvent_setup_customize_title: "Personaliza tu Evento en Vivo",
liveEvent_setup_video_title: "Añade los Recursos a tu Evento",
category_setup_title: "Configuración de Categoría",
category_setup_undertitle: "Completa todos los campos obligatorios",
category_setup_customize_title: "Nombra tu Categoría",
user_setup_title: "Configuración de Usuario",
user_setup_undertitle: "Completa todos los campos obligatorios",
user_setup_customize_title: "Personaliza el Usuario",
course_unpublish_banner: "Este curso no está publicado. No será visible para los Usuarios.",
post_unpublish_banner: "Esta publicación no está publicada. No será visible para los Usuarios.",
liveEvent_unpublish_banner: "Este evento no está publicado. No será visible para los Usuarios.",
category_unpublish_banner: "Esta categoría no está publicada. No será visible para los Usuarios.",
chapter_unpublish_banner: "Este capítulo no está publicado. No será visible para los Usuarios.",
analytics_total_revenue_label: "Ingresos Totales",
analytics_total_sales_label: "Ventas Totales",
customize_NavColors_title: "Personaliza los colores de tu navegación",
customize_navBackgroundColorForm_title: "Color de fondo de la navegación",
customize_navDarkBackgroundColorForm_title: "Color de fondo de la navegación en modo oscuro",
customize_navPrimaryColorForm_title: "Color principal de la navegación",
customize_navDarkPrimaryColorForm_title: "Color principal de la navegación en modo oscuro",
customize_customizeNavigation_title: "Personaliza los colores de tu navegación",
customize_NavColorsDark_title: "Personaliza los colores de tu navegación en modo oscuro",
settings_menu_containersettings_title: "Configuración del contenedor",
settings_menu_navigationdesign_title: "Diseño de la navegación",
settings_backToMenu_button_text: "Volver al menú",
nav_item_browse: "Explorar",
nav_item_dashboard: "Tablero",
nav_item_news: "Noticias",
nav_item_liveEvent: "Evento en Vivo",
nav_item_chat: "Chat",
nav_item_documents: "Documentos",
nav_admin_item_course: "Cursos",
nav_admin_item_posts: "Publicaciones",
nav_admin_item_liveEvents: "Eventos en Vivo",
nav_admin_item_categories: "Categoría",
nav_admin_item_users: "Usuarios",
nav_admin_item_analytics: "Análisis",
nav_admin_item_settings: "Configuraciones",
customize_ImageFormDark_title: "Imagen del contenedor en modo oscuro",
settings_Container_IconForm_title: "Icono del contenedor",
privacy_policy_title: "Política de Privacidad y Términos y Condiciones",
privacy_policy_description: "Para continuar usando nuestra plataforma, revise y acepte nuestra Política de Privacidad y Términos y Condiciones. Su aceptación garantiza que ha leído y comprendido cómo se manejarán sus datos y que acepta las reglas que rigen nuestra plataforma. Valoramos su privacidad y nos esforzamos por proporcionar un entorno seguro para todos los usuarios.",
privacy_policy_button: "Lo he leído y lo acepto",
user_isBannedForm_title: "Estado de Prohibición",
user_isBannedForm_cancel: "Cancelar",
user_isBannedForm_edit: "Editar",
user_isBannedForm_save: "Guardar",
user_setup_settings_title: "Zona de Peligro",
courses_authorForm_cancel: "Cancelar",
courses_authorForm_edit: "Editar Autor",
courses_authorForm_save: "Guardar",
courses_authorForm_placeholder: "p.ej. 'Max Mustermann'",
courses_authorForm_title: "Nombre del autor",
courses_authorForm_empty: "vacio",
};
