export const Espanol: Record<string, string> = {
  documents: "documentos",
  document_hub: "centro de documentos",
  type: "tipo",
  name: "nombre",
  created_at: "creado en",
  administration: "administración",
  create: "crear",
  create_file: "crear archivo",
  create_folder: "crear carpeta",
  create_a_folder: "crear una carpeta",
  public: "público",
  cancel: "cancelar",
  placeholder: "Por favor, introduzca el nombre de la carpeta",
  placeholder_file: "Por favor, introduzca el nombre del archivo",
  edit: "editar",
  file: "archivo",
  upload_file: "subir archivo",
  update: "actualizar",
  save: "guardar",
  rename: "renombrar",
  are_you_sure_you_want_to_delete: "¿Estás seguro de que quieres eliminar?",
  delete: "eliminar",
  a_file: "a archivo",
  a_folder: "a carpeta",
  add: "agregar",
};
