export const Francaise: Record<string, string> = {
  documents: "documents",
  document_hub: "centre de documents",
  type: "type",
  name: "prénom",
  created_at: "créé à",
  administration: "administration",
  create: "créer",
  create_file: "créer un fichier",
  create_folder: "créer un dossier",
  create_a_folder: "créer un dossier",
  public: "public",
  cancel: "annuler",
  placeholder: "Veuillez entrer le nom du dossier",
  placeholder_file: "Veuillez entrer le nom du fichier",
  edit: "modifier",
  file: "fichier",
  upload_file: "télécharger un fichier",
  update: "mettre à jour",
  save: "sauvegarder",
  rename: "renommer",
  are_you_sure_you_want_to_delete: "Êtes-vous sûr de vouloir supprimer",
  delete: "effacer",
  a_file: "un fichier",
  a_folder: "un dossier",
  add: "ajouter",
  navigation_administration_button_text: "Administration",
  navigation_administration_button_text_exit: "Quitter",
  navigation_theme_toggle_light: "Lumière",
  navigation_theme_toggle_dark: "Sombre",
  navigation_theme_toggle_system: "Système",
  navigation_language_toggle_english: "Anglais",
  navigation_language_toggle_german: "Allemand",
  navigation_language_toggle_french: "Français",
  navigation_language_toggle_spanish: "Espagnol",
  navigation_language_toggle_italian: "Italien",
  navigation_language_toggle_portuguese: "Portugais",
  navigation_language_toggle_russian: "Russe",
  navigation_language_toggle_mandarin: "Mandarin",
  navigation_search_placeholder: "Rechercher",
  navigation_footer_text: "Propulsé par",
  navigation_footer_text_product: "Produit",
  search_courseCounter_currentCourses: "Cours existants actuels",
  news_no_posts_found: "Aucun message trouvé",
  news_comments_button_label: "Commentaires",
  news_comments_input_placeholder: "Tapez votre commentaire...",
  news_comments_showmore_label: "Afficher plus +",
  news_comments_reply_button_label: "Répondre",
  live_event_futureAndPast_button_text_future: "Événements futurs",
  live_event_futureAndPast_button_text_past: "Événements passés",
  live_event_filter_button_text: "Filtrer",
  live_event_filter_title: "Filtre d'événements en direct",
  live_event_filter_description: "Vous pouvez filtrer les événements en donnant la date de début et/ou de fin d'un événement.",
  live_event_filter_applyFilter_button_text: "Appliquer le filtre",
  live_event_filter_clearFilter_button_text: "Effacer le filtre",
  courses_createCourse_button_text: "Nouveau Cours",
courses_noCourses_text: "Aucun cours trouvé",
adminTable_previous_button_text: "Précédent",
adminTable_next_button_text: "Suivant",
courses_searchCourses_placeholder: "Filtrer les cours...",
actions_unpublish: "Retirer la publication",
actions_publish: "Publier",
courses_titleForm_title: "Titre du Cours",
courses_titleForm_cancel: "Annuler",
courses_titleForm_edit: "Modifier le Titre",
courses_titleForm_placeholder: "ex. : 'Développement web avancé'",
courses_titleForm_save: "Sauvegarder",
courses_descriptionForm_title: "Description du Cours",
courses_descriptionForm_cancel: "Annuler",
courses_descriptionForm_edit: "Modifier la Description",
courses_descriptionForm_empty: "Aucune Description",
courses_descriptionForm_placeholder: "ex. : 'Ce cours est sur...'",
courses_descriptionForm_save: "Sauvegarder",
course_imageForm_title: "Image du Cours",
courses_imageForm_cancel: "Annuler",
courses_imageForm_add: "Ajouter une Image",
courses_imageForm_edit: "Modifier l'Image",
courses_imageForm_aspectRatioRecoomendation: "Rapport d'aspect recommandé de 16:9",
courses_categoryForm_title: "Catégorie du Cours",
courses_categoryForm_cancel: "Annuler",
courses_categoryForm_edit: "Modifier la Catégorie",
courses_categoryForm_noCategory: "Aucune Catégorie",
courses_categoryForm_save: "Sauvegarder",
courses_chaptersForm_title: "Chapitres du Cours",
courses_chaptersForm_cancel: "Annuler",
courses_chaptersForm_addChapter: "Ajouter un Chapitre",
courses_chaptersForm_placeholder: "ex. : 'Introduction au cours'",
courses_chaptersForm_save: "Créer",
courses_chaptersForm_noChapters: "Aucun Chapitre",
courses_chaptersForm_reorderInstructions: "Glisser et déposer pour réordonner les chapitres",
course_priceForm_title: "Prix du Cours",
courses_priceForm_cancel: "Annuler",
courses_priceForm_edit: "Modifier le Prix",
courses_priceForm_noPrice: "Aucun Prix",
courses_priceForm_placeholder: "Définir un prix pour votre cours",
courses_priceForm_save: "Sauvegarder",
course_attachmentForm_title: "Pièces jointes du Cours",
course_attachmentForm_cancel: "Annuler",
course_attachmentForm_add: "Ajouter un Fichier",
course_attachmentForm_noAttachments: "Aucune Pièce jointe pour le moment",
course_attachmentForm_Recoomendation: "Ajoutez tout ce dont vos étudiants pourraient avoir besoin pour compléter le cours.",
confirmModal_DialogHeader: "Êtes-vous sûr ?",
confirmModal_DialogDescription: "Cette action ne peut pas être annulée.",
confirmModal_DialogConfirm: "Confirmer",
confirmModal_DialogCancel: "Annuler",
chapter_TitleForm_title: "Titre du Chapitre",
chapter_TitleForm_cancel: "Annuler",
chapter_TitleForm_edit: "Modifier le Titre",
chapter_TitleForm_save: "Sauvegarder",
chapter_TitleForm_placeholder: "ex. : 'Introduction au cours'",
chapter_chapterDescriptionForm_title: "Description du Chapitre",
chapter_chapterDescriptionForm_cancel: "Annuler",
chapter_chapterDescriptionForm_edit: "Modifier la Description",
chapter_chapterDescriptionForm_noDescription: "Aucune Description",
chapter_chapterDescriptionForm_save: "Sauvegarder",
chapter_accessForm_title: "Accès au Chapitre",
chapter_accessForm_cancel: "Annuler",
chapter_accessForm_edit: "Modifier l'Accès",
chapter_accessForm_isFree: "Ce chapitre est gratuit.",
chapter_accessForm_isNotFree: "Ce chapitre n'est pas gratuit.",
chapter_accessForm_description: "Cochez cette case si vous souhaitez rendre ce chapitre gratuit.",
chapter_accessForm_save: "Sauvegarder",
chapter_actions_unpublish: "Retirer la publication",
chapter_actions_publish: "Publier",
chapter_VideoForm_title: "Vidéo du Chapitre",
chapter_VideoForm_cancel: "Annuler",
chapter_VideoForm_edit: "Modifier la Vidéo",
chapter_VideoForm_addVideo: "Ajouter une Vidéo",
chapter_VideoForm_placeholder: "Lien de partage Vimeo",
chapter_VideoForm_urlWarning: "Rafraîchissez la page si la vidéo n'apparaît pas.",
post_createPost_button_text: "Créer un Post",
post_noPosts_text: "Aucun post trouvé.",
post_search_placeholder_text: "Filtrer les posts...",
posts_actions_unpublish: "Retirer la publication",
posts_actions_publish: "Publier",
post_TitleForm_title: "Titre de la publication",
post_TitleForm_cancel: "Annuler",
post_TitleForm_edit: "Modifier le Titre",
post_TitleForm_placeholder: "ex. : 'Développement web avancé'",
post_TitleForm_save: "Sauvegarder",
post_DescriptionForm_title: "Description de la Publication",
post_DescriptionForm_cancel: "Annuler",
post_DescriptionForm_edit: "Modifier la Description",
post_DescriptionForm_noDescription: "Aucune Description",
post_DescriptionForm_save: "Sauvegarder",
post_CategoryForm_title: "Catégorie de la publication",
post_CategoryForm_cancel: "Annuler",
post_CategoryForm_edit: "Modifier la catégorie",
post_CategoryForm_noCategory: "Aucune Catégorie",
post_CategoryForm_save: "Sauvegarder",
post_ImageForm_title: "Image de la publication",
post_ImageForm_cancel: "Annuler",
post_ImageForm_add: "Ajouter une Image",
post_ImageForm_edit: "Modifier l'Image",
post_ImageForm_help: "Rapport d'aspect recommandé de 16:9",
categories_search_placeholder_text: "Filtrer les catégories...",
categories_createCategory_button_text: "Nouvelle Catégorie",
categories_noCategories_text: "Aucun résultat.",
categories_TitleForm_title: "Nom de la Catégorie",
categories_TitleForm_cancel: "Annuler",
categories_TitleForm_edit: "Modifier le Nom",
categories_TitleForm_placeholder: "ex. : 'Développement web avancé'",
categories_TitleForm_save: "Sauvegarder",
category_ColorForm_title: "Couleur de la Catégorie",
categories_ColorForm_cancel: "Annuler",
categories_ColorForm_edit: "Modifier",
categories_ColorForm_save: "Sauvegarder",
post_CategoryTypeForm_title: "Type de Catégorie",
post_CategoryTypeForm_isCourseCategory: "Catégorie de Cours",
post_CategoryTypeForm_isNewsCategory: "Catégorie de Nouvelles",
post_CategoryTypeForm_isLiveEventCategory: "Catégorie d'Événement en Direct",
post_CategoryTypeForm_save: "Sauvegarder",
customize_ContainerLinkForm_title: "Lien du Conteneur",
customize_ContainerLinkForm_cancel: "Annuler",
customize_ContainerLinkForm_edit: "Modifier le Titre",
customize_ContainerLinkForm_placeholder: "ex. : 'Développement web avancé'",
customize_ContainerLinkForm_save: "Sauvegarder",
customize_ImageForm_title: "Image du Conteneur",
customize_ImageForm_cancel: "Annuler",
customize_ImageForm_addImage: "Ajouter une Image",
customize_ImageForm_edit: "Modifier l'Image",
customize_ImageForm_imageHint: "Rapport d'aspect recommandé de 16:9",
customize_PrimaryColorForm_title: "Couleur Principale",
customize_PrimaryColorForm_cancel: "Annuler",
customize_PrimaryColorForm_edit: "Modifier",
customize_PrimaryColorForm_save: "Sauvegarder",
users_search_placeholder_text: "Filtrer les profils...",
users_noUsers_text: "Aucun utilisateur.",
user_TitleForm_title: "Nom d'Utilisateur",
user_MailForm_title: "E-Mail de l'Utilisateur",
user_RoleForm_title: "Rôle du Profil",
user_RoleForm_cancel: "Annuler",
user_RoleForm_edit: "Modifier le Rôle",
user_RoleForm_save: "Sauvegarder",
chat_ChatMessages_loading: "Chargement des messages...",
chat_ChatMessages_error: "Quelque chose s'est mal passé !",
chat_ChatMessages_loadPreviousMessages: "Charger les messages précédents",
chat_ChatItem_viewPDF: "Fichier PDF",
chat_ChatItem_edited: "(modifié)",
chat_ChatItem_editMessage: "Message modifié",
chat_ChatItem_saveChanges: "Sauvegarder",
chat_ChatItem_editMessageHint: "Appuyez sur échapper pour annuler, entrer pour sauvegarder",
chat_ChatInput_placeholder: "Message",
chat_initialModal_title: "Créer votre Serveur",
chat_initialModal_description: "Donnez à votre serveur une personnalité avec un nom et une image. Vous pouvez toujours le modifier plus tard.",
chat_initialModal_serverName: "Nom du Serveur",
chat_initialModal_serverName_placeholder: "Entrez le nom du serveur",
chat_initialModal_createServer: "Créer",
chat_serverSection_createChannel: "Créer un Canal",
chat_serverSection_manageMembers: "Gérer les Membres",
chat_server_search_placeholder: "Rechercher",
chat_server_search_notFound: "Aucun Résultat Trouvé",
chat_server_invite: "Inviter des Gens",
chat_server_edit: "Éditer le Serveur",
chat_server_manage_members: "Gérer les Membres",
chat_server_create_channel: "Créer un Canal",
chat_server_delete: "Supprimer le Serveur",
chat_server_addServer: "Ajouter un Serveur",
chat_channel_edit: "Éditer",
chat_channel_delete: "Supprimer",
chat_chatItem_edit: "Éditer",
chat_chatItem_delete: "Supprimer",
chat_socket_reconnecting: "Reconnexion : Sondage toutes les 1s",
chat_socket_connected: "En Direct : Mises à jour en temps réel",
chat_modal_create_server_title: "Personnaliser votre Serveur",
chat_modal_create_server_description: "Donnez à votre serveur une personnalité avec un nom et une image. Vous pouvez toujours le modifier plus tard.",
chat_modal_create_server_name: "Nom du serveur",
chat_modal_create_server_name_placeholder: "Entrez le nom du serveur",
chat_modal_create_server_create: "Créer",
chat_modal_create_channel_title: "Créer un Canal",
chat_modal_create_channel_name: "Nom du canal",
chat_modal_create_channel_name_placeholder: "Entrez le nom du canal",
chat_modal_create_channelType_name: "Type de Canal",
chat_modal_create_channelType_placeholder: "Sélectionnez un type de canal",
chat_modal_create_channel_create: "Créer",
chat_modal_invite_title: "Inviter des Amis",
chat_modal_invite_link_label: "Lien d'invitation au serveur",
chat_modal_invite_new: "Générer un nouveau lien",
chat_modal_manageMembers_title: "Gérer les Membres",
chat_modal_manageMembers_description: "Membres",
chat_modal_manageMembers_role_label: "Rôle",
chat_modal_manageMembers_role_guest: "Invité",
chat_modal_manageMembers_role_moderator: "Modérateur",
chat_modal_manageMembers_kick: "Expulser",
chat_modal_delete_server_title: "Supprimer le Serveur",
chat_modal_delete_server_description_1: "Êtes-vous sûr de vouloir faire cela ?",
chat_modal_delete_server_description_2: "sera définitivement supprimé.",
chat_modal_delete_server_cancel_button: "Annuler",
chat_modal_delete_server_delete_button: "Confirmer",
chat_modal_edit_channel_title: "Éditer le Canal",
chat_modal_edit_channel_name: "Nom du Canal",
chat_modal_edit_channel_name_placeholder: "Entrez le nom du canal",
chat_modal_edit_channel_type: "Type de Canal",
chat_modal_edit_channel_save: "Sauvegarder",
chat_modal_edit_channel_type_placeholder: "Sélectionnez un type de canal",
chat_modal_deleteChannel_title: "Supprimer le Canal",
chat_modal_deleteChannel_description_1: "Êtes-vous sûr de vouloir faire cela ?",
chat_modal_deleteChannel_description_2: "sera définitivement supprimé.",
chat_modal_deleteChannel_cancel_button: "Annuler",
chat_modal_deleteChannel_delete_button: "Confirmer",
chat_modal_leaveServer_title: "Quitter le Serveur",
chat_modal_leaveServer_description_1: "Êtes-vous sûr de vouloir quitter",
chat_modal_leaveServer_cancel: "Annuler",
chat_modal_leaveServer_leave: "Confirmer",
chat_modal_messageFile_title: "Ajouter une pièce jointe",
chat_modal_messageFile_description: "Envoyer un fichier comme message",
chat_modal_messageFile_submit: "Envoyer",
createCourse_title: "Nommer votre Cours",
createCourse_description: "Comment souhaitez-vous nommer votre cours ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
createCourse_form_label: "Titre du cours",
createCourse_form_description: "Que allez-vous enseigner dans ce cours ?",
createCourse_form_placeholder: "ex. : 'Développement web avancé'",
createCourse_cancel: "Annuler",
createCourse_submit: "Continuer",
createPost_title: "Nommer votre Publication",
createPost_description: "Comment souhaitez-vous nommer votre publication ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
createPost_form_label: "Titre de la publication",
createPost_form_placeholder: "ex. : 'Développement web avancé'",
createPost_form_description: "Que souhaitez-vous faire savoir à votre communauté ?",
createPost_cancel: "Annuler",
createPost_submit: "Continuer",
createLiveEvent_title: "Nommer votre Événement en Direct",
createLiveEvent_description: "Comment souhaitez-vous nommer votre événement en direct ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
createLiveEvent_form_label: "Titre de l'événement",
createLiveEvent_form_placeholder: "ex. : 'Développement web avancé'",
createLiveEvent_form_description: "Que montrerez-vous lors de votre événement ?",
createLiveEvent_cancel: "Annuler",
createLiveEvent_submit: "Continuer",
createCategory_title: "Nommer votre Catégorie",
createCategory_description: "Comment souhaitez-vous nommer votre catégorie ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
createCategory_form_label: "Nom de la catégorie",
createCategory_form_placeholder: "ex. : 'Développement web avancé'",
createCategory_form_description: "Que catégoriserez-vous sur votre plateforme ?",
createCategory_cancel: "Annuler",
createCategory_submit: "Sauvegarder",
liveEvent_createEvent_button_text: "Nouvel Événement",
liveEvent_noEvent_text: "Aucun événement trouvé.",
liveEvent_filterEvents_placeholder: "Filtrer les événements...",
infocard_courses: "Cours",
infocard_course: "Cours",
infocard_inprogress: "En cours",
infocard_completed: "Terminé",
no_courses: "Aucun cours trouvé",
customize_customizeCcontainer_title: "Personnalisez votre conteneur",
customize_customizeCcontainer_requiredFields: "Remplissez tous les champs requis",
customize_customizeYourCcontainer: "Personnalisez votre conteneur",
requiredFields: "*requis",
customize_AddImageTitle: "Ajouter une image en tant que logo",
chat_welcome_title: "Bienvenue dans #",
chat_welcome_description: "Ceci est le début du #",
chat_welcome_description2: "canal",
chat_welcome_title_directMessage: "Ceci est le début de votre conversation avec",
serverSidebar_textChannel: "Canaux texte",
serverSidebar_videoChannel: "Canaux vidéo",
serverSidebar_audioChannel: "Canaux audio",
serverSidebar_member: "Membres",
chat_serversection_label_text: "Canaux texte",
chat_serversection_label_audio: "Canaux audio",
chat_serversection_label_video: "Canaux vidéo",
chat_serversection_label_member: "Membres",
chat_server_search_command_placeholder: "Rechercher tous les canaux et membres",
course_setup_title: "Configuration du cours",
course_setup_undertitle: "Remplissez tous les champs requis",
course_setup_course_information_title: "Personnalisez votre cours",
course_setup_price_title: "Vendez votre cours",
course_setup_chapters_title: "Chapitres du cours",
course_setup_attachments_title: "Ressources et pièces jointes",
courses_chapter_backToCourse_button_text: "Retour à la configuration du cours",
courses_chapter_title: "Création de chapitre",
courses_chapter_undertitle: "Remplissez tous les champs",
course_chapter_customize_title: "Personnalisez votre chapitre",
course_chapter_access: "Paramètres d'accès",
course_chapter_video: "Ajouter une vidéo",
courses_setup_free_badge: "Gratuit",
courses_setup_published_text: "Publié",
courses_setup_draft_text: "Brouillon",
post_setup_title: "Configuration de la publication",
post_setup_undertitle: "Remplissez tous les champs requis",
post_setup_customize_title: "Personnalisez votre publication",
post_setup_image_title: "Ajouter une image à votre publication",
liveEvent_PremiumFeature_description: "Pour utiliser les Événements en direct et configurer vos événements numériques et hybrides avec notre logiciel, vous devez utiliser le package de communauté.",
liveEvent_PremiumFeature_button_text: "Acheter le package de communauté",
liveEvent_setup_title: "Configuration de l'événement",
liveEvent_setup_undertitle: "Remplissez tous les champs requis",
liveEvent_setup_customize_title: "Personnalisez votre événement en direct",
liveEvent_setup_video_title: "Ajoutez les ressources à votre événement",
category_setup_title: "Configuration de la catégorie",
category_setup_undertitle: "Remplissez tous les champs requis",
category_setup_customize_title: "Nommez votre catégorie",
user_setup_title: "Configuration de l'utilisateur",
user_setup_undertitle: "Remplissez tous les champs requis",
user_setup_customize_title: "Personnalisez l'utilisateur",
course_unpublish_banner: "Ce cours n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
post_unpublish_banner: "Cette publication n'est pas publiée. Elle ne sera pas visible pour les utilisateurs.",
liveEvent_unpublish_banner: "Cet événement n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
category_unpublish_banner: "Cette catégorie n'est pas publiée. Elle ne sera pas visible pour les utilisateurs.",
chapter_unpublish_banner: "Ce chapitre n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
analytics_total_revenue_label: "Revenu total",
analytics_total_sales_label: "Ventes totales",
};
