export const Francaise: Record<string, string> = {
  documents: "documents",
  document_hub: "centre de documents",
  type: "type",
  name: "prénom",
  created_at: "créé à",
  administration: "administration",
  create: "créer",
  create_file: "créer un fichier",
  create_folder: "créer un dossier",
  create_a_folder: "créer un dossier",
  public: "public",
  cancel: "annuler",
  placeholder: "Veuillez entrer le nom du dossier",
  placeholder_file: "Veuillez entrer le nom du fichier",
  edit: "modifier",
  file: "fichier",
  upload_file: "télécharger un fichier",
  update: "mettre à jour",
  save: "sauvegarder",
  rename: "renommer",
  are_you_sure_you_want_to_delete: "Êtes-vous sûr de vouloir supprimer",
  delete: "effacer",
  a_file: "un fichier",
  a_folder: "un dossier",
  add: "ajouter",
  navigation_administration_button_text: "Administration",
  navigation_administration_button_text_exit: "Quitter",
  navigation_theme_toggle_light: "Lumière",
  navigation_theme_toggle_dark: "Sombre",
  navigation_theme_toggle_system: "Système",
  navigation_language_toggle_english: "Anglais",
  navigation_language_toggle_german: "Allemand",
  navigation_language_toggle_french: "Français",
  navigation_language_toggle_spanish: "Espagnol",
  navigation_language_toggle_italian: "Italien",
  navigation_language_toggle_portuguese: "Portugais",
  navigation_language_toggle_russian: "Russe",
  navigation_language_toggle_mandarin: "Mandarin",
  navigation_search_placeholder: "Rechercher",
  navigation_footer_text: "Propulsé par",
  navigation_footer_text_product: "Produit",
  search_courseCounter_currentCourses: "Cours existants actuels",
  news_no_posts_found: "Aucun message trouvé",
  news_comments_button_label: "Commentaires",
  news_comments_input_placeholder: "Tapez votre commentaire...",
  news_comments_showmore_label: "Afficher plus +",
  news_comments_reply_button_label: "Répondre",
  live_event_futureAndPast_button_text_future: "Événements futurs",
  live_event_futureAndPast_button_text_past: "Événements passés",
  live_event_filter_button_text: "Filtrer",
  live_event_filter_title: "Filtre d'événements en direct",
  live_event_filter_description: "Vous pouvez filtrer les événements en donnant la date de début et/ou de fin d'un événement.",
};
