export const Francaise: Record<string, string> = {
  documents: "documents",
  document_hub: "centre de documents",
  type: "type",
  name: "prénom",
  created_at: "créé à",
  administration: "administration",
  create: "créer",
  create_file: "créer un fichier",
  create_folder: "créer un dossier",
  create_a_folder: "créer un dossier",
  public: "public",
  cancel: "annuler",
  placeholder: "Veuillez entrer le nom du dossier",
  placeholder_file: "Veuillez entrer le nom du fichier",
  edit: "modifier",
  file: "fichier",
  upload_file: "télécharger un fichier",
  update: "mettre à jour",
  save: "sauvegarder",
  rename: "renommer",
  are_you_sure_you_want_to_delete: "Êtes-vous sûr de vouloir supprimer",
  delete: "effacer",
  a_file: "un fichier",
  a_folder: "un dossier",
  add: "ajouter",
};
