export const Italiano: Record<string, string> = {
  documents: "documenti",
  document_hub: "hub dei documenti",
  type: "tipo",
  name: "nome",
  created_at: "creato a",
  administration: "amministrazione",
  create: "creare",
  create_file: "creare file",
  create_folder: "creare cartella",
  create_a_folder: "creare una cartella",
  public: "pubblico",
  cancel: "cancellare",
  placeholder: "Si prega di inserire il nome della cartella",
  placeholder_file: "Si prega di inserire il nome del file",
  edit: "modificare",
  file: "file",
  upload_file: "caricare file",
  update: "aggiornare",
  save: "salvare",
  rename: "rinominare",
  are_you_sure_you_want_to_delete: "Sei sicuro di voler eliminare",
  delete: "eliminare",
  a_file: "un file",
  a_folder: "una cartella",
  add: "aggiungere",
  navigation_administration_button_text: "Amministrazione",
  navigation_administration_button_text_exit: "Esci",
  navigation_theme_toggle_light: "Luce",
  navigation_theme_toggle_dark: "Scuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "Inglese",
  navigation_language_toggle_german: "Tedesco",
  navigation_language_toggle_french: "francese",
  navigation_language_toggle_spanish: "Spagnolo",
  navigation_language_toggle_italian: "Italiano",
  navigation_language_toggle_portuguese: "Portoghese",
  navigation_language_toggle_russian: "Russo",
  navigation_language_toggle_mandarin: "Mandarino",
  navigation_search_placeholder: "Cerca",
  navigation_footer_text: "Fornito da",
  navigation_footer_text_product: "Prodotto",
  search_courseCounter_currentCourses: "Corsi esistenti attuali",
  news_no_posts_found: "Nessun post trovato",
  news_comments_button_label: "Commenti",
  news_comments_input_placeholder: "Digita il tuo commento...",
  news_comments_showmore_label: "Mostra altro +",
  news_comments_reply_button_label: "Rispondi",
  live_event_futureAndPast_button_text_future: "Eventi futuri",
  live_event_futureAndPast_button_text_past: "Eventi passati",
  live_event_filter_button_text: "Filtrare",
  live_event_filter_title: "Filtro eventi dal vivo",
  live_event_filter_description: "Puoi filtrare gli eventi fornendo la data di inizio e/o di fine di un evento.",
  live_event_filter_applyFilter_button_text: "Applica filtro",
  live_event_filter_clearFilter_button_text: "Cancella filtro",
  courses_createCourse_button_text: "Nuovo Corso",
courses_noCourses_text: "Nessun corso trovato",
adminTable_previous_button_text: "Precedente",
adminTable_next_button_text: "Successivo",
courses_searchCourses_placeholder: "Filtra Corsi...",
actions_unpublish: "Rimuovi pubblicazione",
actions_publish: "Pubblica",
courses_titleForm_title: "Titolo del Corso",
courses_titleForm_cancel: "Annulla",
courses_titleForm_edit: "Modifica Titolo",
courses_titleForm_placeholder: "es. 'Sviluppo web avanzato'",
courses_titleForm_save: "Salva",
courses_descriptionForm_title: "Descrizione del Corso",
courses_descriptionForm_cancel: "Annulla",
courses_descriptionForm_edit: "Modifica Descrizione",
courses_descriptionForm_empty: "Nessuna Descrizione",
courses_descriptionForm_placeholder: "es. 'Questo corso tratta di...'",
courses_descriptionForm_save: "Salva",
course_imageForm_title: "Immagine del Corso",
courses_imageForm_cancel: "Annulla",
courses_imageForm_add: "Aggiungi un'Immagine",
courses_imageForm_edit: "Modifica Immagine",
courses_imageForm_aspectRatioRecoomendation: "Rapporto di aspetto consigliato 16:9",
courses_categoryForm_title: "Categoria del Corso",
courses_categoryForm_cancel: "Annulla",
courses_categoryForm_edit: "Modifica Categoria",
courses_categoryForm_noCategory: "Nessuna Categoria",
courses_categoryForm_save: "Salva",
courses_chaptersForm_title: "Capitoli del Corso",
courses_chaptersForm_cancel: "Annulla",
courses_chaptersForm_addChapter: "Aggiungi un Capitolo",
courses_chaptersForm_placeholder: "es. 'Introduzione al corso'",
courses_chaptersForm_save: "Crea",
courses_chaptersForm_noChapters: "Nessun Capitolo",
courses_chaptersForm_reorderInstructions: "Trascina e rilascia per riordinare i capitoli",
course_priceForm_title: "Prezzo del Corso",
courses_priceForm_cancel: "Annulla",
courses_priceForm_edit: "Modifica Prezzo",
courses_priceForm_noPrice: "Nessun Prezzo",
courses_priceForm_placeholder: "Imposta un prezzo per il tuo corso",
courses_priceForm_save: "Salva",
course_attachmentForm_title: "Allegati del Corso",
course_attachmentForm_cancel: "Annulla",
course_attachmentForm_add: "Aggiungi un File",
course_attachmentForm_noAttachments: "Nessun Allegato ancora",
course_attachmentForm_Recoomendation: "Aggiungi qualsiasi cosa i tuoi studenti possano aver bisogno per completare il corso.",
confirmModal_DialogHeader: "Sei sicuro?",
confirmModal_DialogDescription: "Questa azione non può essere annullata.",
confirmModal_DialogConfirm: "Conferma",
confirmModal_DialogCancel: "Annulla",
chapter_TitleForm_title: "Titolo del Capitolo",
chapter_TitleForm_cancel: "Annulla",
chapter_TitleForm_edit: "Modifica Titolo",
chapter_TitleForm_save: "Salva",
chapter_TitleForm_placeholder: "es. 'Introduzione al corso'",
chapter_chapterDescriptionForm_title: "Descrizione del Capitolo",
chapter_chapterDescriptionForm_cancel: "Annulla",
chapter_chapterDescriptionForm_edit: "Modifica Descrizione",
chapter_chapterDescriptionForm_noDescription: "Nessuna Descrizione",
chapter_chapterDescriptionForm_save: "Salva",
chapter_accessForm_title: "Accesso al Capitolo",
chapter_accessForm_cancel: "Annulla",
chapter_accessForm_edit: "Modifica Accesso",
chapter_accessForm_isFree: "Questo capitolo è gratuito.",
chapter_accessForm_isNotFree: "Questo capitolo non è gratuito.",
chapter_accessForm_description: "Seleziona questa casella se vuoi rendere questo capitolo gratuito.",
chapter_accessForm_save: "Salva",
chapter_actions_unpublish: "Rimuovi pubblicazione",
chapter_actions_publish: "Pubblica",
chapter_VideoForm_title: "Video del Capitolo",
chapter_VideoForm_cancel: "Annulla",
chapter_VideoForm_edit: "Modifica Video",
chapter_VideoForm_addVideo: "Aggiungi un Video",
chapter_VideoForm_placeholder: "Link di condivisione Vimeo",
chapter_VideoForm_urlWarning: "Aggiorna la pagina se il video non appare.",
post_createPost_button_text: "Nuovo Post",
post_noPosts_text: "Nessun post trovato.",
post_search_placeholder_text: "Filtra Post...",
posts_actions_unpublish: "Rimuovi pubblicazione",
posts_actions_publish: "Pubblica",
post_TitleForm_title: "Titolo del Post",
post_TitleForm_cancel: "Annulla",
post_TitleForm_edit: "Modifica Titolo",
post_TitleForm_placeholder: "es. 'Sviluppo web avanzato'",
post_TitleForm_save: "Salva",
post_DescriptionForm_title: "Descrizione del Post",
post_DescriptionForm_cancel: "Annulla",
post_DescriptionForm_edit: "Modifica Descrizione",
post_DescriptionForm_noDescription: "Nessuna Descrizione",
post_DescriptionForm_save: "Salva",
post_CategoryForm_title: "Categoria del Post",
post_CategoryForm_cancel: "Annulla",
post_CategoryForm_edit: "Modifica Categoria",
post_CategoryForm_noCategory: "Nessuna Categoria",
post_CategoryForm_save: "Salva",
post_ImageForm_title: "Immagine del Post",
post_ImageForm_cancel: "Annulla",
post_ImageForm_add: "Aggiungi Immagine",
post_ImageForm_edit: "Modifica Immagine",
post_ImageForm_help: "Rapporto di aspetto consigliato 16:9",
categories_search_placeholder_text: "Filtra Categorie...",
categories_createCategory_button_text: "Nuova Categoria",
categories_noCategories_text: "Nessun Risultato.",
categories_TitleForm_title: "Nome Categoria",
categories_TitleForm_cancel: "Annulla",
categories_TitleForm_edit: "Modifica Nome",
categories_TitleForm_placeholder: "es. 'Sviluppo web avanzato'",
categories_TitleForm_save: "Salva",
category_ColorForm_title: "Colore Categoria",
categories_ColorForm_cancel: "Annulla",
categories_ColorForm_edit: "Modifica",
categories_ColorForm_save: "Salva",
post_CategoryTypeForm_title: "Tipo di Categoria",
post_CategoryTypeForm_isCourseCategory: "Categoria Corso",
post_CategoryTypeForm_isNewsCategory: "Categoria Notizie",
post_CategoryTypeForm_isLiveEventCategory: "Categoria Evento dal Vivo",
post_CategoryTypeForm_save: "Salva",
customize_ContainerLinkForm_title: "Link Contenitore",
customize_ContainerLinkForm_cancel: "Annulla",
customize_ContainerLinkForm_edit: "Modifica Titolo",
customize_ContainerLinkForm_placeholder: "es. 'Sviluppo web avanzato'",
customize_ContainerLinkForm_save: "Salva",
customize_ImageForm_title: "Immagine Contenitore",
customize_ImageForm_cancel: "Annulla",
customize_ImageForm_addImage: "Aggiungi un'Immagine",
customize_ImageForm_edit: "Modifica Immagine",
customize_ImageForm_imageHint: "Rapporto di aspetto consigliato 16:9",
customize_PrimaryColorForm_title: "Colore Primario",
customize_PrimaryColorForm_cancel: "Annulla",
customize_PrimaryColorForm_edit: "Modifica",
customize_PrimaryColorForm_save: "Salva",
users_search_placeholder_text: "Filtra Profili...",
users_noUsers_text: "Nessun Utente.",
user_TitleForm_title: "Nome Utente",
user_MailForm_title: "E-Mail Utente",
user_RoleForm_title: "Ruolo Profilo",
user_RoleForm_cancel: "Annulla",
user_RoleForm_edit: "Modifica Ruolo",
user_RoleForm_save: "Salva",
chat_ChatMessages_loading: "Caricamento messaggi...",
chat_ChatMessages_error: "Qualcosa è andato storto!",
chat_ChatMessages_loadPreviousMessages: "Carica messaggi precedenti",
chat_ChatItem_viewPDF: "File PDF",
chat_ChatItem_edited: "(modificato)",
chat_ChatItem_editMessage: "modifica Messaggio",
chat_ChatItem_saveChanges: "Salva",
chat_ChatItem_editMessageHint: "Premi escape per annullare, invio per salvare",
chat_ChatInput_placeholder: "Messaggio",
chat_initialModal_title: "Crea il tuo Server",
chat_initialModal_description: "Dai una personalità al tuo server con un nome e un'immagine. Puoi sempre cambiarlo più tardi.",
chat_initialModal_serverName: "Nome Server",
chat_initialModal_serverName_placeholder: "Inserisci il nome del server",
chat_initialModal_createServer: "Crea",
chat_serverSection_createChannel: "Crea Canale",
chat_serverSection_manageMembers: "Gestisci Membri",
chat_server_search_placeholder: "Cerca",
chat_server_search_notFound: "Nessun Risultato Trovato",
chat_server_invite: "Invita Persone",
chat_server_edit: "Modifica Server",
chat_server_manage_members: "Gestisci Membri",
chat_server_create_channel: "Crea Canale",
chat_server_delete: "Elimina Server",
chat_server_addServer: "Aggiungi un Server",
chat_channel_edit: "Modifica",
chat_channel_delete: "Elimina",
chat_chatItem_edit: "Modifica",
chat_chatItem_delete: "Elimina",
chat_socket_reconnecting: "Riconnessione: polling ogni 1s",
chat_socket_connected: "In Diretta: aggiornamenti in tempo reale",
chat_modal_create_server_title: "Personalizza il tuo Server",
chat_modal_create_server_description: "Dai al tuo server una personalità con un nome e un'immagine. Puoi sempre cambiarlo più tardi.",
chat_modal_create_server_name: "Nome del server",
chat_modal_create_server_name_placeholder: "Inserisci il nome del server",
chat_modal_create_server_create: "Crea",
chat_modal_create_channel_title: "Crea Canale",
chat_modal_create_channel_name: "Nome del Canale",
chat_modal_create_channel_name_placeholder: "Inserisci il nome del canale",
chat_modal_create_channelType_name: "Tipo di Canale",
chat_modal_create_channelType_placeholder: "Seleziona un tipo di canale",
chat_modal_create_channel_create: "Crea",
chat_modal_invite_title: "Invita Amici",
chat_modal_invite_link_label: "Link di invito al server",
chat_modal_invite_new: "Genera un nuovo link",
chat_modal_manageMembers_title: "Gestisci Membri",
chat_modal_manageMembers_description: "Membri",
chat_modal_manageMembers_role_label: "Ruolo",
chat_modal_manageMembers_role_guest: "Ospite",
chat_modal_manageMembers_role_moderator: "Moderatore",
chat_modal_manageMembers_kick: "Espelli",
chat_modal_delete_server_title: "Elimina Server",
chat_modal_delete_server_description_1: "Sei sicuro di voler fare questo?",
chat_modal_delete_server_description_2: "sarà eliminato permanentemente.",
chat_modal_delete_server_cancel_button: "Annulla",
chat_modal_delete_server_delete_button: "Conferma",
chat_modal_edit_channel_title: "Modifica Canale",
chat_modal_edit_channel_name: "Nome del Canale",
chat_modal_edit_channel_name_placeholder: "Inserisci il nome del canale",
chat_modal_edit_channel_type: "Tipo di Canale",
chat_modal_edit_channel_save: "Salva",
chat_modal_edit_channel_type_placeholder: "Seleziona un tipo di canale",
chat_modal_deleteChannel_title: "Elimina Canale",
chat_modal_deleteChannel_description_1: "Sei sicuro di voler fare questo?",
chat_modal_deleteChannel_description_2: "sarà eliminato permanentemente.",
chat_modal_deleteChannel_cancel_button: "Annulla",
chat_modal_deleteChannel_delete_button: "Conferma",
chat_modal_leaveServer_title: "Lascia Server",
chat_modal_leaveServer_description_1: "Sei sicuro di voler lasciare",
chat_modal_leaveServer_cancel: "Annulla",
chat_modal_leaveServer_leave: "Conferma",
chat_modal_messageFile_title: "Aggiungi un allegato",
chat_modal_messageFile_description: "Invia un file come messaggio",
chat_modal_messageFile_submit: "Invia",
createCourse_title: "Nomina il tuo Corso",
createCourse_description: "Come desideri nominare il tuo corso? Non preoccuparti, potrai cambiarlo in seguito.",
createCourse_form_label: "Titolo del Corso",
createCourse_form_description: "Cosa insegnerai in questo corso?",
createCourse_form_placeholder: "es. 'Sviluppo web avanzato'",
createCourse_cancel: "Annulla",
createCourse_submit: "Continua",
createPost_title: "Nomina il tuo Post",
createPost_description: "Come desideri nominare il tuo post? Non preoccuparti, potrai cambiarlo in seguito.",
createPost_form_label: "Titolo del Post",
createPost_form_placeholder: "es. 'Sviluppo web avanzato'",
createPost_form_description: "Cosa vuoi far sapere alla tua Comunità?",
createPost_cancel: "Annulla",
createPost_submit: "Continua",
createLiveEvent_title: "Nomina il tuo Evento Live",
createLiveEvent_description: "Come desideri nominare il tuo evento live? Non preoccuparti, potrai cambiarlo in seguito.",
createLiveEvent_form_label: "Titolo dell'Evento",
createLiveEvent_form_placeholder: "es. 'Sviluppo web avanzato'",
createLiveEvent_form_description: "Cosa mostrerai nel tuo evento?",
createLiveEvent_cancel: "Annulla",
createLiveEvent_submit: "Continua",
createCategory_title: "Nomina la tua Categoria",
createCategory_description: "Come desideri nominare la tua categoria? Non preoccuparti, potrai cambiarlo in seguito.",
createCategory_form_label: "Nome della Categoria",
createCategory_form_placeholder: "es. 'Sviluppo web avanzato'",
createCategory_form_description: "Cosa categorizzerai sulla tua piattaforma?",
createCategory_cancel: "Annulla",
createCategory_submit: "Salva",
liveEvent_createEvent_button_text: "Nuovo Evento Live",
liveEvent_noEvent_text: "Nessun evento trovato.",
liveEvent_filterEvents_placeholder: "Filtra Eventi...",
infocard_courses: "Corsi",
infocard_course: "Corso",
infocard_inprogress: "In corso",
infocard_completed: "Completato",
no_courses: "Nessun corso trovato",
customize_customizeCcontainer_title: "Personalizza il tuo Contenitore",
customize_customizeCcontainer_requiredFields: "Completa tutti i campi obbligatori",
customize_customizeYourCcontainer: "Personalizza il tuo Contenitore",
requiredFields: "*obbligatorio",
customize_AddImageTitle: "Aggiungi un'Immagine come Logo",
chat_welcome_title: "Benvenuto su #",
chat_welcome_description: "Questo è l'inizio del canale #",
chat_welcome_description2: "canale",
chat_welcome_title_directMessage: "Questo è l'inizio della tua conversazione con",
serverSidebar_textChannel: "Canali Testuali",
serverSidebar_videoChannel: "Canali Video",
serverSidebar_audioChannel: "Canali Audio",
serverSidebar_member: "Membri",
chat_serversection_label_text: "Canali Testuali",
chat_serversection_label_audio: "Canali Audio",
chat_serversection_label_video: "Canali Video",
chat_serversection_label_member: "Membri",
chat_server_search_command_placeholder: "Cerca tra tutti i canali e membri",
course_setup_title: "Configurazione del Corso",
course_setup_undertitle: "Completa tutti i campi obbligatori",
course_setup_course_information_title: "Personalizza il tuo corso",
course_setup_price_title: "Vendi il tuo Corso",
course_setup_chapters_title: "Capitoli del Corso",
course_setup_attachments_title: "Risorse & Allegati",
courses_chapter_backToCourse_button_text: "Torna alla Configurazione del Corso",
courses_chapter_title: "Creazione Capitolo",
courses_chapter_undertitle: "Completa tutti i campi",
course_chapter_customize_title: "Personalizza il tuo Capitolo",
course_chapter_access: "Impostazioni di Accesso",
course_chapter_video: "Aggiungi un Video",
courses_setup_free_badge: "Gratuito",
courses_setup_published_text: "Pubblicato",
courses_setup_draft_text: "Bozza",
post_setup_title: "Configurazione Post",
post_setup_undertitle: "Completa tutti i campi obbligatori",
post_setup_customize_title: "Personalizza il tuo Post",
post_setup_image_title: "Aggiungi un'Immagine al tuo Post",
liveEvent_PremiumFeature_description: "Per utilizzare gli Eventi dal Vivo e configurare i tuoi eventi digitali e ibridi con il nostro software, devi utilizzare il pacchetto comunitario.",
liveEvent_PremiumFeature_button_text: "Acquista Pacchetto Comunitario",
liveEvent_setup_title: "Configurazione dell'Evento dal Vivo",
liveEvent_setup_undertitle: "Completa tutti i campi obbligatori",
liveEvent_setup_customize_title: "Personalizza il tuo Evento dal Vivo",
liveEvent_setup_video_title: "Aggiungi le Risorse al tuo Evento",
category_setup_title: "Configurazione della Categoria",
category_setup_undertitle: "Completa tutti i campi obbligatori",
category_setup_customize_title: "Nomina la tua Categoria",
user_setup_title: "Configurazione Utente",
user_setup_undertitle: "Completa tutti i campi obbligatori",
user_setup_customize_title: "Personalizza l'Utente",
course_unpublish_banner: "Questo corso non è pubblicato. Non sarà visibile agli Utenti.",
post_unpublish_banner: "Questo post non è pubblicato. Non sarà visibile agli Utenti.",
liveEvent_unpublish_banner: "Questo evento non è pubblicato. Non sarà visibile agli Utenti.",
category_unpublish_banner: "Questa categoria non è pubblicata. Non sarà visibile agli Utenti.",
chapter_unpublish_banner: "Questo capitolo non è pubblicato. Non sarà visibile agli Utenti.",
analytics_total_revenue_label: "Ricavi Totali",
analytics_total_sales_label: "Vendite Totali",
customize_NavColors_title: "Personalizza i colori della tua navigazione",
customize_navBackgroundColorForm_title: "Colore di sfondo della navigazione",
customize_navDarkBackgroundColorForm_title: "Colore di sfondo della navigazione in modalità scura",
customize_navPrimaryColorForm_title: "Colore primario della navigazione",
customize_navDarkPrimaryColorForm_title: "Colore primario della navigazione in modalità scura",
customize_customizeNavigation_title: "Personalizza i colori della tua navigazione",
customize_NavColorsDark_title: "Personalizza i colori della tua navigazione in modalità scura",
settings_menu_containersettings_title: "Impostazioni del contenitore",
settings_menu_navigationdesign_title: "Design della navigazione",
settings_backToMenu_button_text: "Torna al menu",
nav_item_browse: "Sfoglia",
nav_item_dashboard: "Cruscotto",
nav_item_news: "Notizie",
nav_item_liveEvent: "Evento dal Vivo",
nav_item_chat: "Chat",
nav_item_documents: "Documenti",
nav_admin_item_course: "Corsi",
nav_admin_item_posts: "Post",
nav_admin_item_liveEvents: "Eventi dal Vivo",
nav_admin_item_categories: "Categoria",
nav_admin_item_users: "Utenti",
nav_admin_item_analytics: "Analisi",
nav_admin_item_settings: "Impostazioni",
customize_ImageFormDark_title: "Immagine del contenitore in modalità scura",
settings_Container_IconForm_title: "Icona del contenitore",
privacy_policy_title: "Politica sulla Privacy e Termini e Condizioni",
privacy_policy_description: "Per continuare a utilizzare la nostra piattaforma, si prega di esaminare e accettare la nostra Politica sulla Privacy e i Termini e Condizioni. La tua accettazione garantisce che hai letto e compreso come saranno gestiti i tuoi dati e accetti le regole che governano la nostra piattaforma. Valutiamo la tua privacy e ci sforziamo di fornire un ambiente sicuro per tutti gli utenti.",
privacy_policy_button: "Ho letto e accetto",
user_isBannedForm_title: "Stato di Bannato",
user_isBannedForm_cancel: "Annulla",
user_isBannedForm_edit: "Modifica",
user_isBannedForm_save: "Salva",
user_setup_settings_title: "Zona Pericolosa",
courses_authorForm_cancel: "Anulla",
courses_authorForm_edit: "Modifica autore",
courses_authorForm_save: "Salva",
courses_authorForm_placeholder: "es. 'Max Mustermann'",
courses_authorForm_title: "Nome autore",
courses_authorForm_empty: "vuoto",
infocard_completedChapters: "Capitoli Completati",
infocard_currentOnlineUsers: "Utenti Online Attuali",
profile_manageAccount: "Gestisci account",
profile_signOut: "Disconnettersi",
profile_change_customize_username: "Cambia il tuo nome utente",
profile_TitleForm_title: "Nome utente",
profile_TitleForm_cancel: "Annulla",
profile_TitleForm_edit: "Modifica",
profile_TitleForm_placeholder: "NomeUtente123",
profile_TitleForm_save: "Salva",
courses_list_backToDashboard_button_text: "Torna al Dashboard",
dashboard_courseTable_CourseStatus_Title: "Stato del Corso",
dashboard_courseTable_courseName: "Nome del Corso",
dashboard_courseTable_paid: "Pagato",
dashboard_courseTable_progress: "Progresso",
dashboard_courseTable_chapter: "Capitolo",
dashboard_courseTable_action: "Azione",
dashboard_courseTable_viewAllCourses_button_text: "Visualizza tutto",
dashboard_courseTable_viewCourse_button_text: "CERCARE",
chapter_aboutcourse_title: "Informazioni sul Capitolo",
chapter_CourseDocuments_Title: "Documenti del Corso",
courses_setup_backToCourseAdminList_button_text: "Torna alla Vista dei Corsi",
post_setup_backToPostAdminList_button_text: "Torna alla Vista dei Post",
liveEvent_setup_backToEventAdminList_button_text: "Torna alla Vista degli Eventi in Diretta",
category_setup_backToCategoryAdminList_button_text: "Torna alla Vista delle Categorie",
user_setup_backToUserAdminList_button_text: "Torna alla Vista degli Utenti",
settings_backToAdminSettings_button_text: "Torna alla Vista delle Impostazioni",
navigation_language_tooltip: "Lingue",
navigation_mode_tooltip: "Modalità",
navigation_administration_tooltip: "Amministrazione",
navigation_profile_tooltip: "Profilo",
privacy_policy_link: "Informativa sulla Privacy",
privacy_termsOfService_link: "Termini di Servizio",
chapter_attachments_NoDocuments: "Nessun documento",
};
