export const Italiano: Record<string, string> = {
  documents: "documenti",
  document_hub: "hub dei documenti",
  type: "tipo",
  name: "nome",
  created_at: "creato a",
  administration: "amministrazione",
  create: "creare",
  create_file: "creare file",
  create_folder: "creare cartella",
  create_a_folder: "creare una cartella",
  public: "pubblico",
  cancel: "cancellare",
  placeholder: "Si prega di inserire il nome della cartella",
  placeholder_file: "Si prega di inserire il nome del file",
  edit: "modificare",
  file: "file",
  upload_file: "caricare file",
  update: "aggiornare",
  save: "salvare",
  rename: "rinominare",
  are_you_sure_you_want_to_delete: "Sei sicuro di voler eliminare",
  delete: "eliminare",
  a_file: "un file",
  a_folder: "una cartella",
  add: "aggiungere",
  navigation_administration_button_text: "Amministrazione",
  navigation_administration_button_text_exit: "Esci",
  navigation_theme_toggle_light: "Luce",
  navigation_theme_toggle_dark: "Scuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "Inglese",
  navigation_language_toggle_german: "Tedesco",
  navigation_language_toggle_french: "francese",
  navigation_language_toggle_spanish: "Spagnolo",
  navigation_language_toggle_italian: "Italiano",
  navigation_language_toggle_portuguese: "Portoghese",
  navigation_language_toggle_russian: "Russo",
  navigation_language_toggle_mandarin: "Mandarino",
  navigation_search_placeholder: "Cerca",
  navigation_footer_text: "Fornito da",
  navigation_footer_text_product: "Prodotto",
  search_courseCounter_currentCourses: "Corsi esistenti attuali",
  news_no_posts_found: "Nessun post trovato",
  news_comments_button_label: "Commenti",
  news_comments_input_placeholder: "Digita il tuo commento...",
  news_comments_showmore_label: "Mostra altro +",
  news_comments_reply_button_label: "Rispondi",
  live_event_futureAndPast_button_text_future: "Eventi futuri",
  live_event_futureAndPast_button_text_past: "Eventi passati",
  live_event_filter_button_text: "Filtrare",
  live_event_filter_title: "Filtro eventi dal vivo",
  live_event_filter_description: "Puoi filtrare gli eventi fornendo la data di inizio e/o di fine di un evento.",
  live_event_filter_applyFilter_button_text: "Applica filtro",
  live_event_filter_clearFilter_button_text: "Cancella filtro",
};
