export const Italiano: Record<string, string> = {
  documents: "documenti",
  document_hub: "hub dei documenti",
  type: "tipo",
  name: "nome",
  created_at: "creato a",
  administration: "amministrazione",
  create: "creare",
  create_file: "creare file",
  create_folder: "creare cartella",
  create_a_folder: "creare una cartella",
  public: "pubblico",
  cancel: "cancellare",
  placeholder: "Si prega di inserire il nome della cartella",
  placeholder_file: "Si prega di inserire il nome del file",
  edit: "modificare",
  file: "file",
  upload_file: "caricare file",
  update: "aggiornare",
  save: "salvare",
  rename: "rinominare",
  are_you_sure_you_want_to_delete: "Sei sicuro di voler eliminare",
  delete: "eliminare",
  a_file: "un file",
  a_folder: "una cartella",
  add: "aggiungere",
};
