export const Mandarin: Record<string, string> = {
  documents: "文件",
  document_hub: "文件中心",
  type: "类型",
  name: "名字",
  created_at: "创建于",
  administration: "管理",
  create: "创造",
  create_file: "创建文件",
  create_folder: "创建文件夹",
  create_a_folder: "创建文件夹",
  public: "公共",
  cancel: "取消",
  placeholder: "请输入文件夹名称",
  placeholder_file: "请输入文件名称",
  edit: "编辑",
  file: "文件",
  upload_file: "上传文件",
  update: "更新",
  save: "保存",
  rename: "重命名",
  are_you_sure_you_want_to_delete: "你确定要删除",
  delete: "删除",
  a_file: "一个文件",
  a_folder: "一个文件夹",
  add: "添加",
};
