export const Portugues: Record<string, string> = {
  documents: "documentos",
  document_hub: "hub de documentos",
  type: "tipo",
  name: "nome",
  created_at: "criado em",
  administration: "administração",
  create: "criar",
  create_file: "criar arquivo",
  create_folder: "criar pasta",
  create_a_folder: "criar uma pasta",
  public: "público",
  cancel: "cancelar",
  placeholder: "Por favor, insira o nome da pasta",
  placeholder_file: "Por favor, insira o nome do arquivo",
  edit: "editar",
  file: "arquivo",
  upload_file: "carregar arquivo",
  update: "atualizar",
  save: "salvar",
  rename: "renomear",
  are_you_sure_you_want_to_delete: "Você tem certeza de que deseja excluir",
  delete: "excluir",
  a_file: "um arquivo",
  a_folder: "uma pasta",
  add: "adicionar",
};
