export const Portugues: Record<string, string> = {
  documents: "documentos",
  document_hub: "hub de documentos",
  type: "tipo",
  name: "nome",
  created_at: "criado em",
  administration: "administração",
  create: "criar",
  create_file: "criar arquivo",
  create_folder: "criar pasta",
  create_a_folder: "criar uma pasta",
  public: "público",
  cancel: "cancelar",
  placeholder: "Por favor, insira o nome da pasta",
  placeholder_file: "Por favor, insira o nome do arquivo",
  edit: "editar",
  file: "arquivo",
  upload_file: "carregar arquivo",
  update: "atualizar",
  save: "salvar",
  rename: "renomear",
  are_you_sure_you_want_to_delete: "Você tem certeza de que deseja excluir",
  delete: "excluir",
  a_file: "um arquivo",
  a_folder: "uma pasta",
  add: "adicionar",
  navigation_administration_button_text: "Administração",
  navigation_administration_button_text_exit: "Sair",
  navigation_theme_toggle_light: "Luz",
  navigation_theme_toggle_dark: "Escuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "Inglês",
  navigation_language_toggle_german: "Alemão",
  navigation_language_toggle_french: "Francês",
  navigation_language_toggle_spanish: "Espanhol",
  navigation_language_toggle_italian: "Italiano",
  navigation_language_toggle_portuguese: "Português",
  navigation_language_toggle_russian: "Russo",
  navigation_language_toggle_mandarin: "Mandarim",
  navigation_search_placeholder: "Pesquisar",
  navigation_footer_text: "Desenvolvido por",
  navigation_footer_text_product: "Produto",
  search_courseCounter_currentCourses: "Cursos existentes atuais",
  news_no_posts_found: "Nenhuma postagem encontrada",
  news_comments_button_label: "Comentários",
  news_comments_input_placeholder: "Digite seu comentário...",
  news_comments_showmore_label: "Mostrar mais +",
  news_comments_reply_button_label: "Responder",
  live_event_futureAndPast_button_text_future: "Eventos Futuros",
  live_event_futureAndPast_button_text_past: "Eventos Passados",
  live_event_filter_button_text: "Filtrar",
  live_event_filter_title: "Filtro de eventos ao vivo",
  live_event_filter_description: "Você pode filtrar eventos informando a data de início e/ou término de um evento.",
  live_event_filter_applyFilter_button_text: "Aplicar Filtro",
  live_event_filter_clearFilter_button_text: "Limpar Filtro",
};
