export const Portugues: Record<string, string> = {
  documents: "documentos",
  document_hub: "hub de documentos",
  type: "tipo",
  name: "nome",
  created_at: "criado em",
  administration: "administração",
  create: "criar",
  create_file: "criar arquivo",
  create_folder: "criar pasta",
  create_a_folder: "criar uma pasta",
  public: "público",
  cancel: "cancelar",
  placeholder: "Por favor, insira o nome da pasta",
  placeholder_file: "Por favor, insira o nome do arquivo",
  edit: "editar",
  file: "arquivo",
  upload_file: "carregar arquivo",
  update: "atualizar",
  save: "salvar",
  rename: "renomear",
  are_you_sure_you_want_to_delete: "Você tem certeza de que deseja excluir",
  delete: "excluir",
  a_file: "um arquivo",
  a_folder: "uma pasta",
  add: "adicionar",
  navigation_administration_button_text: "Administração",
  navigation_administration_button_text_exit: "Sair",
  navigation_theme_toggle_light: "Luz",
  navigation_theme_toggle_dark: "Escuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "Inglês",
  navigation_language_toggle_german: "Alemão",
  navigation_language_toggle_french: "Francês",
  navigation_language_toggle_spanish: "Espanhol",
  navigation_language_toggle_italian: "Italiano",
  navigation_language_toggle_portuguese: "Português",
  navigation_language_toggle_russian: "Russo",
  navigation_language_toggle_mandarin: "Mandarim",
  navigation_search_placeholder: "Pesquisar",
  navigation_footer_text: "Desenvolvido por",
  navigation_footer_text_product: "Produto",
  search_courseCounter_currentCourses: "Cursos existentes atuais",
  news_no_posts_found: "Nenhuma postagem encontrada",
  news_comments_button_label: "Comentários",
  news_comments_input_placeholder: "Digite seu comentário...",
  news_comments_showmore_label: "Mostrar mais +",
  news_comments_reply_button_label: "Responder",
  live_event_futureAndPast_button_text_future: "Eventos Futuros",
  live_event_futureAndPast_button_text_past: "Eventos Passados",
  live_event_filter_button_text: "Filtrar",
  live_event_filter_title: "Filtro de eventos ao vivo",
  live_event_filter_description: "Você pode filtrar eventos informando a data de início e/ou término de um evento.",
  live_event_filter_applyFilter_button_text: "Aplicar Filtro",
  live_event_filter_clearFilter_button_text: "Limpar Filtro",
  courses_createCourse_button_text: "Novo Curso",
courses_noCourses_text: "Nenhum curso encontrado",
adminTable_previous_button_text: "Anterior",
adminTable_next_button_text: "Próximo",
courses_searchCourses_placeholder: "Filtrar Cursos...",
actions_unpublish: "Despublicar",
actions_publish: "Publicar",
courses_titleForm_title: "Título do Curso",
courses_titleForm_cancel: "Cancelar",
courses_titleForm_edit: "Editar Título",
courses_titleForm_placeholder: "ex: 'Desenvolvimento web avançado'",
courses_titleForm_save: "Salvar",
courses_descriptionForm_title: "Descrição do Curso",
courses_descriptionForm_cancel: "Cancelar",
courses_descriptionForm_edit: "Editar Descrição",
courses_descriptionForm_empty: "Sem Descrição",
courses_descriptionForm_placeholder: "ex: 'Este curso é sobre...'",
courses_descriptionForm_save: "Salvar",
course_imageForm_title: "Imagem do Curso",
courses_imageForm_cancel: "Cancelar",
courses_imageForm_add: "Adicionar uma Imagem",
courses_imageForm_edit: "Editar Imagem",
courses_imageForm_aspectRatioRecoomendation: "Relação de aspecto recomendada de 16:9",
courses_categoryForm_title: "Categoria do Curso",
courses_categoryForm_cancel: "Cancelar",
courses_categoryForm_edit: "Editar Categoria",
courses_categoryForm_noCategory: "Sem Categoria",
courses_categoryForm_save: "Salvar",
courses_chaptersForm_title: "Capítulos do Curso",
courses_chaptersForm_cancel: "Cancelar",
courses_chaptersForm_addChapter: "Adicionar um Capítulo",
courses_chaptersForm_placeholder: "ex: 'Introdução ao curso'",
courses_chaptersForm_save: "Criar",
courses_chaptersForm_noChapters: "Sem Capítulos",
courses_chaptersForm_reorderInstructions: "Arrastar e soltar para reordenar os capítulos",
course_priceForm_title: "Preço do Curso",
courses_priceForm_cancel: "Cancelar",
courses_priceForm_edit: "Editar Preço",
courses_priceForm_noPrice: "Sem Preço",
courses_priceForm_placeholder: "Definir um preço para o seu curso",
courses_priceForm_save: "Salvar",
course_attachmentForm_title: "Anexos do Curso",
course_attachmentForm_cancel: "Cancelar",
course_attachmentForm_add: "Adicionar um Arquivo",
course_attachmentForm_noAttachments: "Sem Anexos ainda",
course_attachmentForm_Recoomendation: "Adicione qualquer coisa que seus alunos possam precisar para completar o curso.",
confirmModal_DialogHeader: "Você tem certeza?",
confirmModal_DialogDescription: "Esta ação não pode ser desfeita.",
confirmModal_DialogConfirm: "Confirmar",
confirmModal_DialogCancel: "Cancelar",
chapter_TitleForm_title: "Título do Capítulo",
chapter_TitleForm_cancel: "Cancelar",
chapter_TitleForm_edit: "Editar Título",
chapter_TitleForm_save: "Salvar",
chapter_TitleForm_placeholder: "ex: 'Introdução ao curso'",
chapter_chapterDescriptionForm_title: "Descrição do Capítulo",
chapter_chapterDescriptionForm_cancel: "Cancelar",
chapter_chapterDescriptionForm_edit: "Editar Descrição",
chapter_chapterDescriptionForm_noDescription: "Sem Descrição",
chapter_chapterDescriptionForm_save: "Salvar",
chapter_accessForm_title: "Acesso ao Capítulo",
chapter_accessForm_cancel: "Cancelar",
chapter_accessForm_edit: "Editar Acesso",
chapter_accessForm_isFree: "Este capítulo é gratuito.",
chapter_accessForm_isNotFree: "Este capítulo não é gratuito.",
chapter_accessForm_description: "Marque esta caixa se você quer tornar este capítulo gratuito.",
chapter_accessForm_save: "Salvar",
chapter_actions_unpublish: "Despublicar",
chapter_actions_publish: "Publicar",
chapter_VideoForm_title: "Vídeo do Capítulo",
chapter_VideoForm_cancel: "Cancelar",
chapter_VideoForm_edit: "Editar Vídeo",
chapter_VideoForm_addVideo: "Adicionar um Vídeo",
chapter_VideoForm_placeholder: "Link de compartilhamento do Vimeo",
chapter_VideoForm_urlWarning: "Atualize a página se o vídeo não aparecer.",
post_createPost_button_text: "Nova Publicação",
post_noPosts_text: "Nenhuma publicação encontrada.",
post_search_placeholder_text: "Filtrar Publicações...",
posts_actions_unpublish: "Despublicar",
posts_actions_publish: "Publicar",
post_TitleForm_title: "Título da Publicação",
post_TitleForm_cancel: "Cancelar",
post_TitleForm_edit: "Editar Título",
post_TitleForm_placeholder: "ex: 'Desenvolvimento web avançado'",
post_TitleForm_save: "Salvar",
post_DescriptionForm_title: "Descrição da Postagem",
post_DescriptionForm_cancel: "Cancelar",
post_DescriptionForm_edit: "Editar Descrição",
post_DescriptionForm_noDescription: "Sem Descrição",
post_DescriptionForm_save: "Salvar",
post_CategoryForm_title: "Categoria da Postagem",
post_CategoryForm_cancel: "Cancelar",
post_CategoryForm_edit: "Editar Categoria",
post_CategoryForm_noCategory: "Sem Categoria",
post_CategoryForm_save: "Salvar",
post_ImageForm_title: "Imagem da Postagem",
post_ImageForm_cancel: "Cancelar",
post_ImageForm_add: "Adicionar Imagem",
post_ImageForm_edit: "Editar Imagem",
post_ImageForm_help: "Recomenda-se proporção de 16:9",
categories_search_placeholder_text: "Filtrar categorias...",
categories_createCategory_button_text: "Nova Categoria",
categories_noCategories_text: "Sem Resultados.",
categories_TitleForm_title: "Nome da Categoria",
categories_TitleForm_cancel: "Cancelar",
categories_TitleForm_edit: "Editar Nome",
categories_TitleForm_placeholder: "ex.: 'Desenvolvimento web avançado'",
categories_TitleForm_save: "Salvar",
category_ColorForm_title: "Cor da Categoria",
categories_ColorForm_cancel: "Cancelar",
categories_ColorForm_edit: "Editar",
categories_ColorForm_save: "Salvar",
post_CategoryTypeForm_title: "Tipo de Categoria",
post_CategoryTypeForm_isCourseCategory: "Categoria de Curso",
post_CategoryTypeForm_isNewsCategory: "Categoria de Notícias",
post_CategoryTypeForm_isLiveEventCategory: "Categoria de Evento ao Vivo",
post_CategoryTypeForm_save: "Salvar",
customize_ContainerLinkForm_title: "Link do Contêiner",
customize_ContainerLinkForm_cancel: "Cancelar",
customize_ContainerLinkForm_edit: "Editar Título",
customize_ContainerLinkForm_placeholder: "ex.: 'Desenvolvimento web avançado'",
customize_ContainerLinkForm_save: "Salvar",
customize_ImageForm_title: "Imagem do Contêiner",
customize_ImageForm_cancel: "Cancelar",
customize_ImageForm_addImage: "Adicionar uma Imagem",
customize_ImageForm_edit: "Editar Imagem",
customize_ImageForm_imageHint: "Proporção recomendada de 16:9",
customize_PrimaryColorForm_title: "Cor Primária",
customize_PrimaryColorForm_cancel: "Cancelar",
customize_PrimaryColorForm_edit: "Editar",
customize_PrimaryColorForm_save: "Salvar",
users_search_placeholder_text: "Filtrar perfis...",
users_noUsers_text: "Sem Usuários.",
user_TitleForm_title: "Nome de Usuário",
user_MailForm_title: "E-mail do Usuário",
user_RoleForm_title: "Função do Perfil",
user_RoleForm_cancel: "Cancelar",
user_RoleForm_edit: "Editar Função",
user_RoleForm_save: "Salvar",
chat_ChatMessages_loading: "Carregando mensagens...",
chat_ChatMessages_error: "Algo deu errado!",
chat_ChatMessages_loadPreviousMessages: "Carregar mensagens anteriores",
chat_ChatItem_viewPDF: "Arquivo PDF",
chat_ChatItem_edited: "(editado)",
chat_ChatItem_editMessage: "mensagem editada",
chat_ChatItem_saveChanges: "Salvar",
chat_ChatItem_editMessageHint: "Pressione 'escape' para cancelar, 'enter' para salvar",
chat_ChatInput_placeholder: "Mensagem",
chat_initialModal_title: "Criar seu Servidor",
chat_initialModal_description: "Dê uma personalidade ao seu servidor com um nome e uma imagem. Você sempre pode mudar isso mais tarde.",
chat_initialModal_serverName: "Nome do Servidor",
chat_initialModal_serverName_placeholder: "Insira o nome do servidor",
chat_initialModal_createServer: "Criar",
chat_serverSection_createChannel: "Criar Canal",
chat_serverSection_manageMembers: "Gerenciar Membros",
chat_server_search_placeholder: "Pesquisar",
chat_server_search_notFound: "Nenhum Resultado Encontrado",
chat_server_invite: "Convidar Pessoas",
chat_server_edit: "Editar Servidor",
chat_server_manage_members: "Gerenciar Membros",
chat_server_create_channel: "Criar Canal",
chat_server_delete: "Excluir Servidor",
chat_server_addServer: "Adicionar um Servidor",
chat_channel_edit: "Editar",
chat_channel_delete: "Excluir",
chat_chatItem_edit: "Editar",
chat_chatItem_delete: "Excluir",
chat_socket_reconnecting: "Reconectando: Polling a cada 1s",
chat_socket_connected: "Ao Vivo",
chat_modal_create_server_title: "Personalizar seu Servidor",
chat_modal_create_server_description: "Dê uma personalidade ao seu servidor com um nome e uma imagem. Você sempre pode mudar isso mais tarde.",
chat_modal_create_server_name: "Nome do servidor",
chat_modal_create_server_name_placeholder: "Insira o nome do servidor",
chat_modal_create_server_create: "Criar",
chat_modal_create_channel_title: "Criar Canal",
chat_modal_create_channel_name: "Nome do Canal",
chat_modal_create_channel_name_placeholder: "Insira o nome do canal",
chat_modal_create_channelType_name: "Tipo de Canal",
chat_modal_create_channelType_placeholder: "Selecione um tipo de canal",
chat_modal_create_channel_create: "Criar",
chat_modal_invite_title: "Convidar Amigos",
chat_modal_invite_link_label: "Link de convite para do servidor",
chat_modal_invite_new: "Gerar um novo link",
chat_modal_manageMembers_title: "Gerir Membros",
chat_modal_manageMembers_description: "Membros",
chat_modal_manageMembers_role_label: "Papel",
chat_modal_manageMembers_role_guest: "Convidado",
chat_modal_manageMembers_role_moderator: "Moderador",
chat_modal_manageMembers_kick: "Expulsar",
chat_modal_delete_server_title: "Eliminar Servidor",
chat_modal_delete_server_description_1: "Tem certeza de que quer fazer isso?",
chat_modal_delete_server_description_2: "será permanentemente excluído.",
chat_modal_delete_server_cancel_button: "Cancelar",
chat_modal_delete_server_delete_button: "Confirmar",
chat_modal_edit_channel_title: "Editar Canal",
chat_modal_edit_channel_name: "Nome do Canal",
chat_modal_edit_channel_name_placeholder: "Digite o nome do canal",
chat_modal_edit_channel_type: "Tipo de Canal",
chat_modal_edit_channel_save: "Salvar",
chat_modal_edit_channel_type_placeholder: "Selecione um tipo de canal",
chat_modal_deleteChannel_title: "Excluir Canal",
chat_modal_deleteChannel_description_1: "Tem certeza de que quer fazer isso?",
chat_modal_deleteChannel_description_2: "será permanentemente excluído.",
chat_modal_deleteChannel_cancel_button: "Cancelar",
chat_modal_deleteChannel_delete_button: "Confirmar",
chat_modal_leaveServer_title: "Sair do Servidor",
chat_modal_leaveServer_description_1: "Tem certeza de que quer sair",
chat_modal_leaveServer_cancel: "Cancelar",
chat_modal_leaveServer_leave: "Confirmar",
chat_modal_messageFile_title: "Adicionar um anexo",
chat_modal_messageFile_description: "Enviar um arquivo como mensagem",
chat_modal_messageFile_submit: "Enviar",
createCourse_title: "Nomear seu Curso",
createCourse_description: "Como gostaria de nomear seu curso? Não se preocupe, você pode mudar isso mais tarde.",
createCourse_form_label: "Título do Curso",
createCourse_form_description: "O que você ensinará neste curso?",
createCourse_form_placeholder: "ex.: 'Desenvolvimento Web Avançado'",
createCourse_cancel: "Cancelar",
createCourse_submit: "Continuar",
createPost_title: "Nomear sua Publicação",
createPost_description: "Como gostaria de nomear sua publicação? Não se preocupe, você pode mudar isso mais tarde.",
createPost_form_label: "Título da Publicação",
createPost_form_placeholder: "ex.: 'Desenvolvimento Web Avançado'",
createPost_form_description: "O que você quer que sua comunidade saiba?",
createPost_cancel: "Cancelar",
createPost_submit: "Continuar",
createLiveEvent_title: "Nomear seu Evento ao Vivo",
createLiveEvent_description: "Como gostaria de nomear seu evento ao vivo? Não se preocupe, você pode mudar isso mais tarde.",
createLiveEvent_form_label: "Título do Evento",
createLiveEvent_form_placeholder: "ex.: 'Desenvolvimento Web Avançado'",
createLiveEvent_form_description: "O que você mostrará no seu evento?",
createLiveEvent_cancel: "Cancelar",
createLiveEvent_submit: "Continuar",
createCategory_title: "Nomear sua Categoria",
createCategory_description: "Como gostaria de nomear sua categoria? Não se preocupe, você pode mudar isso mais tarde.",
createCategory_form_label: "Nome da Categoria",
createCategory_form_placeholder: "ex.: 'Desenvolvimento Web Avançado'",
createCategory_form_description: "O que você categorizará na sua plataforma?",
createCategory_cancel: "Cancelar",
createCategory_submit: "Salvar",
liveEvent_createEvent_button_text: "Novo Evento",
liveEvent_noEvent_text: "Nenhum evento encontrado.",
liveEvent_filterEvents_placeholder: "Filtrar Eventos...",
infocard_courses: "Cursos",
infocard_course: "Curso",
infocard_inprogress: "Em Andamento",
infocard_completed: "Concluído",
no_courses: "Nenhum curso encontrado",
customize_customizeCcontainer_title: "Personalize seu Contêiner",
customize_customizeCcontainer_requiredFields: "Complete todos os campos obrigatórios",
customize_customizeYourCcontainer: "Personalize seu Contêiner",
requiredFields: "*obrigatório",
customize_AddImageTitle: "Adicione uma Imagem como Logotipo",
chat_welcome_title: "Bem-vindo a #",
chat_welcome_description: "Este é o início do canal #",
chat_welcome_description2: "canal",
chat_welcome_title_directMessage: "Este é o início de sua conversa com",
serverSidebar_textChannel: "Canais de Texto",
serverSidebar_videoChannel: "Canais de Vídeo",
serverSidebar_audioChannel: "Canais de Áudio",
serverSidebar_member: "Membros",
chat_serversection_label_text: "Canais de Texto",
chat_serversection_label_audio: "Canais de Áudio",
chat_serversection_label_video: "Canais de Vídeo",
chat_serversection_label_member: "Membros",
chat_server_search_command_placeholder: "Pesquisar todos os canais e membros",
course_setup_title: "Configuração do Curso",
course_setup_undertitle: "Complete todos os campos obrigatórios",
course_setup_course_information_title: "Personalize seu curso",
course_setup_price_title: "Venda seu Curso",
course_setup_chapters_title: "Capítulos do Curso",
course_setup_attachments_title: "Recursos & Anexos",
courses_chapter_backToCourse_button_text: "Voltar para Configuração do Curso",
courses_chapter_title: "Criação de Capítulo",
courses_chapter_undertitle: "Complete todos os campos",
course_chapter_customize_title: "Personalize seu Capítulo",
course_chapter_access: "Configurações de Acesso",
course_chapter_video: "Adicionar um Vídeo",
courses_setup_free_badge: "Grátis",
courses_setup_published_text: "Publicado",
courses_setup_draft_text: "Rascunho",
post_setup_title: "Configuração de Postagem",
post_setup_undertitle: "Complete todos os campos obrigatórios",
post_setup_customize_title: "Personalize sua Postagem",
post_setup_image_title: "Adicione uma Imagem à sua Postagem",
liveEvent_PremiumFeature_description: "Para usar Eventos Ao Vivo e configurar seus eventos digitais e híbridos com nosso software, você precisa usar o pacote da comunidade.",
liveEvent_PremiumFeature_button_text: "Comprar Pacote da Comunidade",
liveEvent_setup_title: "Configuração de Evento Ao Vivo",
liveEvent_setup_undertitle: "Complete todos os campos obrigatórios",
liveEvent_setup_customize_title: "Personalize seu Evento Ao Vivo",
liveEvent_setup_video_title: "Adicione os Recursos ao seu Evento",
category_setup_title: "Configuração de Categoria",
category_setup_undertitle: "Complete todos os campos obrigatórios",
category_setup_customize_title: "Nomeie sua Categoria",
user_setup_title: "Configuração do Usuário",
user_setup_undertitle: "Complete todos os campos obrigatórios",
user_setup_customize_title: "Personalize o Usuário",
course_unpublish_banner: "Este curso não está publicado. Não será visível para os Usuários.",
post_unpublish_banner: "Esta postagem não está publicada. Não será visível para os Usuários.",
liveEvent_unpublish_banner: "Este evento não está publicado. Não será visível para os Usuários.",
category_unpublish_banner: "Esta categoria não está publicada. Não será visível para os Usuários.",
chapter_unpublish_banner: "Este capítulo não está publicado. Não será visível para os Usuários.",
analytics_total_revenue_label: "Receita Total",
analytics_total_sales_label: "Vendas Totais",
customize_NavColors_title: "Personalize as cores da sua navegação",
customize_navBackgroundColorForm_title: "Cor de fundo da navegação",
customize_navDarkBackgroundColorForm_title: "Cor de fundo da navegação em modo escuro",
customize_navPrimaryColorForm_title: "Cor primária da navegação",
customize_navDarkPrimaryColorForm_title: "Cor primária da navegação em modo escuro",
customize_customizeNavigation_title: "Personalize as cores da sua navegação",
customize_NavColorsDark_title: "Personalize as cores da sua navegação em modo escuro",
settings_menu_containersettings_title: "Configurações do contêiner",
settings_menu_navigationdesign_title: "Design da navegação",
settings_backToMenu_button_text: "Voltar ao menu",
nav_item_browse: "Navegar",
nav_item_dashboard: "Painel",
nav_item_news: "Notícias",
nav_item_liveEvent: "Evento ao Vivo",
nav_item_chat: "Chat",
nav_item_documents: "Documentos",
nav_admin_item_course: "Cursos",
nav_admin_item_posts: "Postagens",
nav_admin_item_liveEvents: "Eventos ao Vivo",
nav_admin_item_categories: "Categoria",
nav_admin_item_users: "Usuários",
nav_admin_item_analytics: "Análises",
nav_admin_item_settings: "Configurações",
customize_ImageFormDark_title: "Imagem do contêiner em modo escuro",
settings_Container_IconForm_title: "Ícone do contêiner",
privacy_policy_title: "Política de Privacidade e Termos e Condições",
privacy_policy_description: "Para continuar a usar a nossa plataforma, por favor revise e aceite a nossa Política de Privacidade e Termos e Condições. A sua aceitação garante que você leu e compreendeu como os seus dados serão tratados e concorda com as regras que regem a nossa plataforma. Valorizamos a sua privacidade e esforçamo-nos para proporcionar um ambiente seguro para todos os usuários.",
privacy_policy_button: "Eu li e aceito",
user_isBannedForm_title: "Estado de Banimento",
user_isBannedForm_cancel: "Cancelar",
user_isBannedForm_edit: "Editar",
user_isBannedForm_save: "Salvar",
user_setup_settings_title: "Zona de Perigo",
courses_authorForm_cancel: "Cancelar",
courses_authorForm_edit: "Editar Autor",
courses_authorForm_save: "Salvar",
courses_authorForm_placeholder: "por ex. 'Max Mustermann'",
courses_authorForm_title: "Nome do autor",
courses_authorForm_empty: "vazio",
infocard_completedChapters: "Capítulos Completados",
infocard_currentOnlineUsers: "Usuários Online Atuais",
profile_manageAccount: "Gerenciar conta",
profile_signOut: "Sair",
profile_change_customize_username: "Alterar seu nome de usuário",
profile_TitleForm_title: "Nome de usuário",
profile_TitleForm_cancel: "Cancelar",
profile_TitleForm_edit: "Editar",
profile_TitleForm_placeholder: "NomeUsuario123",
profile_TitleForm_save: "Salvar",
courses_list_backToDashboard_button_text: "Voltar ao Painel",
dashboard_courseTable_CourseStatus_Title: "Status do Curso",
dashboard_courseTable_courseName: "Nome do Curso",
dashboard_courseTable_paid: "Pago",
dashboard_courseTable_progress: "Progresso",
dashboard_courseTable_chapter: "Capítulo",
dashboard_courseTable_action: "Ação",
dashboard_courseTable_viewAllCourses_button_text: "Ver todos",
dashboard_courseTable_viewCourse_button_text: "PROCURAR",
chapter_aboutcourse_title: "Sobre o Capítulo",
chapter_CourseDocuments_Title: "Documentos do Curso",
courses_setup_backToCourseAdminList_button_text: "Voltar para a Visão Geral do Curso",
post_setup_backToPostAdminList_button_text: "Voltar para a Visão Geral das Postagens",
liveEvent_setup_backToEventAdminList_button_text: "Voltar para a Visão Geral dos Eventos ao Vivo",
category_setup_backToCategoryAdminList_button_text: "Voltar para a Visão Geral das Categorias",
user_setup_backToUserAdminList_button_text: "Voltar para a Visão Geral dos Usuários",
settings_backToAdminSettings_button_text: "Voltar para a Visão Geral das Configurações",
navigation_language_tooltip: "Idiomas",
navigation_mode_tooltip: "Modo",
navigation_administration_tooltip: "Administração",
navigation_profile_tooltip: "Perfil",
privacy_policy_link: "Política de Privacidade",
privacy_termsOfService_link: "Termos de Serviço",
chapter_attachments_NoDocuments: "Nenhum documento",
nav_item_career: "Carreira",
nav_item_calendar: "Calendário",
nav_item_knowledgeHub: "Centro de Conhecimento",
profile_OnlineStatus_Online: "Online",
profile_OnlineStatus_Away: "Não disponível",
profile_OnlineStatus_DoNotDisturb: "Não perturbe",
profile_OnlineStatus_Invisible: "Invisível",
profile_OnlineStatus_Offline: "Offline",
profile_status_text: "Status",
profile_help: "Ajuda",
course_chapter_author_text: "Autor -",
live_event_filter_start_date_text: "Data de Início",
live_event_filter_end_date_text: "Data de Término",
chapter_aboutevent_title: "Sobre o Evento",
chat_server_leave: "Sair Servidor",
settings_menu_design_title: "botão Design",
customize_customizeContainer_title: "Personalize as cores do seu contêiner",
customize_PrimaryButtonColors_title: "Personalize a cor do seu botão primário",
customize_PrimaryButtonColorsDark_title: "Personalize a cor do seu botão primário em modo escuro",
customize_PrimaryButtonColorForm_title: "Cor do Bot",
customize_PrimaryButtonColorForm_cancel: "Cancelar",
customize_PrimaryButtonColorForm_edit: "Editar",
customize_PrimaryButtonColorForm_save: "Salvar",
customize_DarkPrimaryButtonColorForm_title: "Cor do Botão Primário em Modo Escuro",
customize_ThemeColorForm_title: "Cor do contorno do tema",
customize_ThemeColorForm_cancel: "Cancelar",
customize_ThemeColorForm_edit: "Editar",
customize_ThemeColorForm_save: "Salvar",
customize_ThemeColorsDark_title: "Personalize a cor do seu tema para o modo escuro",
customize_DarkThemeColorForm_title: "Cor do contorno do tema para o modo escuro",
dashboard_popularChapter_chapterName_text: "Nome do capítulo",
dashboard_popularChapter_courseName_text: "Nome do curso",
dashboard_popularChapter_likes_text: "Curtidas",
dashboard_popularChapter_comments_text: "Comentários",
dashboard_popularChapter_action_text: "Ação",
};
