export const Russian: Record<string, string> = {
  documents: "документы",
  document_hub: "документ хаб",
  type: "тип",
  name: "имя",
  created_at: "создано в",
  administration: "администрация",
  create: "создать",
  create_file: "создать файл",
  create_folder: "создать папку",
  create_a_folder: "создать папку",
  public: "общественный",
  cancel: "отменить",
  placeholder: "Пожалуйста, введите имя папки",
  placeholder_file: "Пожалуйста, введите имя файла",
  edit: "редактировать",
  file: "файл",
  upload_file: "загрузить файл",
  update: "обновить",
  save: "сохранить",
  rename: "переименовать",
  are_you_sure_you_want_to_delete: "Вы уверены, что хотите удалить",
  delete: "удалить",
  a_file: "файл",
  a_folder: "папка",
  add: "добавить",
  navigation_administration_button_text: "Администрирование",
  navigation_administration_button_text_exit: "Выход",
  navigation_theme_toggle_light: "Свет",
  navigation_theme_toggle_dark: "Темный",
  navigation_theme_toggle_system: "Система",
  navigation_language_toggle_english: "Английский",
  navigation_language_toggle_german: "Немецкий",
  navigation_language_toggle_french: "Французский",
  navigation_language_toggle_spanish: "Испанский",
  navigation_language_toggle_italian: "Итальянский",
  navigation_language_toggle_portuguese: "Португальский",
  navigation_language_toggle_russian: "Русский",
  navigation_language_toggle_mandarin: "Мандарин",
  navigation_search_placeholder: "Поиск",
  navigation_footer_text: "При поддержке",
  navigation_footer_text_product: "Продукт",
  search_courseCounter_currentCourses: "Существующие курсы",
  news_no_posts_found: "Сообщений не найдено",
  news_comments_button_label: "Комментарии",
  news_comments_input_placeholder: "Введите комментарий...",
  news_comments_showmore_label: "Показать больше +",
  news_comments_reply_button_label: "Ответить",
  live_event_futureAndPast_button_text_future: "Будущие события",
  live_event_futureAndPast_button_text_past: "Прошлые события",
  live_event_filter_button_text: "Фильтр",
  live_event_filter_title: "Фильтр живых событий",
  live_event_filter_description: "Вы можете фильтровать события, указав дату начала и/или окончания события.",
  live_event_filter_applyFilter_button_text: "Применить фильтр",
  live_event_filter_clearFilter_button_text: "Очистить фильтр",
  courses_createCourse_button_text: "Новый курс",
courses_noCourses_text: "Курсы не найдены",
adminTable_previous_button_text: "Предыдущий",
adminTable_next_button_text: "Следующий",
courses_searchCourses_placeholder: "Фильтровать курсы...",
actions_unpublish: "Снять с публикации",
actions_publish: "Опубликовать",
courses_titleForm_title: "Название курса",
courses_titleForm_cancel: "Отмена",
courses_titleForm_edit: "Редактировать название",
courses_titleForm_placeholder: "например, 'Продвинутая веб-разработка'",
courses_titleForm_save: "Сохранить",
courses_descriptionForm_title: "Описание курса",
courses_descriptionForm_cancel: "Отмена",
courses_descriptionForm_edit: "Редактировать описание",
courses_descriptionForm_empty: "Описание отсутствует",
courses_descriptionForm_placeholder: "например, 'Этот курс о...'",
courses_descriptionForm_save: "Сохранить",
course_imageForm_title: "Изображение курса",
courses_imageForm_cancel: "Отмена",
courses_imageForm_add: "Добавить изображение",
courses_imageForm_edit: "Редактировать изображение",
courses_imageForm_aspectRatioRecoomendation: "Рекомендуемое соотношение сторон 16:9",
courses_categoryForm_title: "Категория курса",
courses_categoryForm_cancel: "Отмена",
courses_categoryForm_edit: "Редактировать категорию",
courses_categoryForm_noCategory: "Категория отсутствует",
courses_categoryForm_save: "Сохранить",
courses_chaptersForm_title: "Главы курса",
courses_chaptersForm_cancel: "Отмена",
courses_chaptersForm_addChapter: "Добавить главу",
courses_chaptersForm_placeholder: "например, 'Введение в курс'",
courses_chaptersForm_save: "Создать",
courses_chaptersForm_noChapters: "Главы отсутствуют",
courses_chaptersForm_reorderInstructions: "Перетащите для изменения порядка глав",
course_priceForm_title: "Цена курса",
courses_priceForm_cancel: "Отмена",
courses_priceForm_edit: "Редактировать цену",
courses_priceForm_noPrice: "Цена отсутствует",
courses_priceForm_placeholder: "Установите цену для вашего курса",
courses_priceForm_save: "Сохранить",
course_attachmentForm_title: "Материалы курса",
course_attachmentForm_cancel: "Отмена",
course_attachmentForm_add: "Добавить файл",
course_attachmentForm_noAttachments: "Материалы отсутствуют",
course_attachmentForm_Recoomendation: "Добавьте все, что может понадобиться вашим студентам для прохождения курса.",
confirmModal_DialogHeader: "Вы уверены?",
confirmModal_DialogDescription: "Это действие нельзя отменить.",
confirmModal_DialogConfirm: "Подтвердить",
confirmModal_DialogCancel: "Отмена",
chapter_TitleForm_title: "Название главы",
chapter_TitleForm_cancel: "Отмена",
chapter_TitleForm_edit: "Редактировать название",
chapter_TitleForm_save: "Сохранить",
chapter_TitleForm_placeholder: "например, 'Введение в курс'",
chapter_chapterDescriptionForm_title: "Описание главы",
chapter_chapterDescriptionForm_cancel: "Отмена",
chapter_chapterDescriptionForm_edit: "Редактировать описание",
chapter_chapterDescriptionForm_noDescription: "Описание отсутствует",
chapter_chapterDescriptionForm_save: "Сохранить",
chapter_accessForm_title: "Доступ к главе",
chapter_accessForm_cancel: "Отмена",
chapter_accessForm_edit: "Редактировать доступ",
chapter_accessForm_isFree: "Эта глава бесплатна.",
chapter_accessForm_isNotFree: "Эта глава платная.",
chapter_accessForm_description: "Отметьте этот пункт, если хотите сделать эту главу бесплатной.",
chapter_accessForm_save: "Сохранить",
chapter_actions_unpublish: "Снять публикации",
chapter_actions_publish: "Опубликовать",
chapter_VideoForm_title: "Видео главы",
chapter_VideoForm_cancel: "Отмена",
chapter_VideoForm_edit: "Редактировать видео",
chapter_VideoForm_addVideo: "Добавить видео",
chapter_VideoForm_placeholder: "Ссылка для обмена на Vimeo",
chapter_VideoForm_urlWarning: "Обновите страницу, если видео не появляется.",
post_createPost_button_text: "Создать новый пост",
post_noPosts_text: "Посты не найдены.",
post_search_placeholder_text: "Фильтровать посты...",
posts_actions_unpublish: "Снять с публикации",
posts_actions_publish: "Опубликовать",
post_TitleForm_title: "Название поста",
post_TitleForm_cancel: "Отмена",
post_TitleForm_edit: "Редактировать название",
post_TitleForm_placeholder: "например, 'Продвинутая веб-разработка'",
post_TitleForm_save: "Сохранить",
post_DescriptionForm_title: "Описание поста",
post_DescriptionForm_cancel: "Отмена",
post_DescriptionForm_edit: "Редактировать описание",
post_DescriptionForm_noDescription: "Описание отсутствует",
post_DescriptionForm_save: "Сохранить",
post_CategoryForm_title: "Категория поста",
post_CategoryForm_cancel: "Отмена",
post_CategoryForm_edit: "Редактировать категорию",
post_CategoryForm_noCategory: "Категория отсутствует",
post_CategoryForm_save: "Сохранить",
post_ImageForm_title: "Изображение поста",
post_ImageForm_cancel: "Отмена",
post_ImageForm_add: "Добавить изображение",
post_ImageForm_edit: "Редактировать изображение",
post_ImageForm_help: "Рекомендуется соотношение сторон 16:9",
categories_search_placeholder_text: "Фильтровать категории...",
categories_createCategory_button_text: "Новая категория",
categories_noCategories_text: "Результаты отсутствуют.",
categories_TitleForm_title: "Название категории",
categories_TitleForm_cancel: "Отмена",
categories_TitleForm_edit: "Редактировать название",
categories_TitleForm_placeholder: "например, 'Продвинутая веб-разработка'",
categories_TitleForm_save: "Сохранить",
category_ColorForm_title: "Цвет категории",
categories_ColorForm_cancel: "Отмена",
categories_ColorForm_edit: "Редактировать",
categories_ColorForm_save: "Сохранить",
post_CategoryTypeForm_title: "Тип категории",
post_CategoryTypeForm_isCourseCategory: "Категория курса",
post_CategoryTypeForm_isNewsCategory: "Категория новостей",
post_CategoryTypeForm_isLiveEventCategory: "Категория живого мероприятия",
post_CategoryTypeForm_save: "Сохранить",
customize_ContainerLinkForm_title: "Ссылка контейнера",
customize_ContainerLinkForm_cancel: "Отмена",
customize_ContainerLinkForm_edit: "Редактировать заголовок",
customize_ContainerLinkForm_placeholder: "например, 'Продвинутая веб-разработка'",
customize_ContainerLinkForm_save: "Сохранить",
customize_ImageForm_title: "Изображение контейнера",
customize_ImageForm_cancel: "Отмена",
customize_ImageForm_addImage: "Добавить изображение",
customize_ImageForm_edit: "Редактировать изображение",
customize_ImageForm_imageHint: "Рекомендуется соотношение сторон 16:9",
customize_PrimaryColorForm_title: "Основной цвет",
customize_PrimaryColorForm_cancel: "Отмена",
customize_PrimaryColorForm_edit: "Редактировать",
customize_PrimaryColorForm_save: "Сохранить",
users_search_placeholder_text: "Фильтровать профили...",
users_noUsers_text: "Пользователи не найдены.",
user_TitleForm_title: "Имя пользователя",
user_MailForm_title: "Электронная почта пользователя",
user_RoleForm_title: "Роль профиля",
user_RoleForm_cancel: "Отмена",
user_RoleForm_edit: "Редактировать роль",
user_RoleForm_save: "Сохранить",
chat_ChatMessages_loading: "Загрузка сообщений...",
chat_ChatMessages_error: "Произошла ошибка!",
chat_ChatMessages_loadPreviousMessages: "Загрузить предыдущие сообщения",
chat_ChatItem_viewPDF: "Файл PDF",
chat_ChatItem_edited: "(отредактировано)",
chat_ChatItem_editMessage: "редактировать сообщение",
chat_ChatItem_saveChanges: "Сохранить",
chat_ChatItem_editMessageHint: "Нажмите escape для отмены, enter для сохранения",
chat_ChatInput_placeholder: "Сообщение",
chat_initialModal_title: "Создайте ваш сервер",
chat_initialModal_description: "Придайте вашему серверу индивидуальность с помощью имени и изображения. Вы всегда можете изменить это позже.",
chat_initialModal_serverName: "Имя сервера",
chat_initialModal_serverName_placeholder: "Введите имя сервера",
chat_initialModal_createServer: "Создать",
chat_serverSection_createChannel: "Создать канал",
chat_serverSection_manageMembers: "Управление участниками",
chat_server_search_placeholder: "Поиск",
chat_server_search_notFound: "Результаты не найдены",
chat_server_invite: "Пригласить людей",
chat_server_edit: "Редактировать сервер",
chat_server_manage_members: "Управлять участниками",
chat_server_create_channel: "Создать канал",
chat_server_delete: "Удалить сервер",
chat_server_addServer: "Добавить сервер",
chat_channel_edit: "Редактировать",
chat_channel_delete: "Удалить",
chat_chatItem_edit: "Редактировать",
chat_chatItem_delete: "Удалить",
chat_socket_reconnecting: "Переподключение: опрос каждые 1 секунду",
chat_socket_connected: "В реальном времени: обновления в режиме онлайн",
chat_modal_create_server_title: "Настроить ваш сервер",
chat_modal_create_server_description: "Придайте вашему серверу индивидуальность с помощью имени и изображения. Вы всегда можете изменить это позже.",
chat_modal_create_server_name: "Имя сервера",
chat_modal_create_server_name_placeholder: "Введите имя сервера",
chat_modal_create_server_create: "Создать",
chat_modal_create_channel_title: "Создать канал",
chat_modal_create_channel_name: "Имя канала",
chat_modal_create_channel_name_placeholder: "Введите имя канала",
chat_modal_create_channelType_name: "Тип канала",
chat_modal_create_channelType_placeholder: "Выберите тип канала",
chat_modal_create_channel_create: "Создать",
chat_modal_invite_title: "Пригласить друзей",
chat_modal_invite_link_label: "Ссылка для приглашения на сервер",
chat_modal_invite_new: "Сгенерировать новую ссылку",
chat_modal_manageMembers_title: "Управление участниками",
chat_modal_manageMembers_description: "Участники",
chat_modal_manageMembers_role_label: "Роль",
chat_modal_manageMembers_role_guest: "Гость",
chat_modal_manageMembers_role_moderator: "Модератор",
chat_modal_manageMembers_kick: "Исключить",
chat_modal_delete_server_title: "Удалить сервер",
chat_modal_delete_server_description_1: "Вы уверены, что хотите это сделать?",
chat_modal_delete_server_description_2: "будет удален навсегда.",
chat_modal_delete_server_cancel_button: "Отмена",
chat_modal_delete_server_delete_button: "Подтвердить",
chat_modal_edit_channel_title: "Редактировать канал",
chat_modal_edit_channel_name: "Имя канала",
chat_modal_edit_channel_name_placeholder: "Введите имя канала",
chat_modal_edit_channel_type: "Тип канала",
chat_modal_edit_channel_save: "Сохранить",
chat_modal_edit_channel_type_placeholder: "Выберите тип канала",
chat_modal_deleteChannel_title: "Удалить канал",
chat_modal_deleteChannel_description_1: "Вы уверены, что хотите это сделать?",
chat_modal_deleteChannel_description_2: "будет удален навсегда.",
chat_modal_deleteChannel_cancel_button: "Отмена",
chat_modal_deleteChannel_delete_button: "Подтвердить",
chat_modal_leaveServer_title: "Покинуть сервер",
chat_modal_leaveServer_description_1: "Вы уверены, что хотите уйти",
chat_modal_leaveServer_cancel: "Отмена",
chat_modal_leaveServer_leave: "Подтвердить",
chat_modal_messageFile_title: "Добавить вложение",
chat_modal_messageFile_description: "Отправить файл как сообщение",
chat_modal_messageFile_submit: "Отправить",
createCourse_title: "Назовите ваш курс",
createCourse_description: "Как вы хотите назвать ваш курс? Не волнуйтесь, вы всегда можете изменить это позже.",
createCourse_form_label: "Название курса",
createCourse_form_description: "Что вы будете преподавать на этом курсе?",
createCourse_form_placeholder: "например, 'Продвинутая веб-разработка'",
createCourse_cancel: "Отмена",
createCourse_submit: "Продолжить",
createPost_title: "Назовите ваш пост",
createPost_description: "Как вы хотите назвать ваш пост? Не волнуйтесь, вы всегда можете изменить это позже.",
createPost_form_label: "Название поста",
createPost_form_placeholder: "например, 'Продвинутая веб-разработка'",
createPost_form_description: "Что вы хотите донести до вашего сообщества?",
createPost_cancel: "Отмена",
createPost_submit: "Продолжить",
createLiveEvent_title: "Назовите ваше живое мероприятие",
createLiveEvent_description: "Как вы хотите назвать ваше живое мероприятие? Не волнуйтесь, вы всегда можете изменить это позже.",
createLiveEvent_form_label: "Название мероприятия",
createLiveEvent_form_placeholder: "например, 'Продвинутая веб-разработка'",
createLiveEvent_form_description: "Что вы покажете на вашем мероприятии?",
createLiveEvent_cancel: "Отмена",
createLiveEvent_submit: "Продолжить",
createCategory_title: "Назовите вашу категорию",
createCategory_description: "Как вы хотите назвать вашу категорию? Не волнуйтесь, вы всегда можете изменить это позже.",
createCategory_form_label: "Имя категории",
createCategory_form_placeholder: "например, 'Продвинутая веб-разработка'",
createCategory_form_description: "Что вы будете категоризировать на вашей платформе?",
createCategory_cancel: "Отмена",
createCategory_submit: "Сохранить",
liveEvent_createEvent_button_text: "Новое Прямое Событие",
liveEvent_noEvent_text: "События не найдены.",
liveEvent_filterEvents_placeholder: "Фильтровать События...",
infocard_courses: "Курсы",
infocard_course: "Курс",
infocard_inprogress: "В процессе",
infocard_completed: "Завершено",
no_courses: "Курсы не найдены",
customize_customizeCcontainer_title: "Настройте ваш контейнер",
customize_customizeCcontainer_requiredFields: "Заполните все обязательные поля",
customize_customizeYourCcontainer: "Настройте ваш контейнер",
requiredFields: "*обязательно",
customize_AddImageTitle: "Добавьте изображение в качестве логотипа",
chat_welcome_title: "Добро пожаловать в #",
chat_welcome_description: "Это начало канала #",
chat_welcome_description2: "канал",
chat_welcome_title_directMessage: "Это начало вашего разговора с",
serverSidebar_textChannel: "Текстовые каналы",
serverSidebar_videoChannel: "Видеоканалы",
serverSidebar_audioChannel: "Аудиоканалы",
serverSidebar_member: "Участники",
chat_serversection_label_text: "Текстовые каналы",
chat_serversection_label_audio: "Аудиоканалы",
chat_serversection_label_video: "Видеоканалы",
chat_serversection_label_member: "Участники",
chat_server_search_command_placeholder: "Поиск по всем каналам и участникам",
course_setup_title: "Настройка курса",
course_setup_undertitle: "Заполните все обязательные поля",
course_setup_course_information_title: "Настройте ваш курс",
course_setup_price_title: "Продайте ваш курс",
course_setup_chapters_title: "Главы курса",
course_setup_attachments_title: "Ресурсы и вложения",
courses_chapter_backToCourse_button_text: "Вернуться к настройке курса",
courses_chapter_title: "Создание главы",
courses_chapter_undertitle: "Заполните все поля",
course_chapter_customize_title: "Настройте вашу главу",
course_chapter_access: "Настройки доступа",
course_chapter_video: "Добавить видео",
courses_setup_free_badge: "Бесплатно",
courses_setup_published_text: "Опубликовано",
courses_setup_draft_text: "Черновик",
post_setup_title: "Настройка поста",
post_setup_undertitle: "Заполните все обязательные поля",
post_setup_customize_title: "Настройте ваш пост",
post_setup_image_title: "Добавьте изображение к вашему посту",
liveEvent_PremiumFeature_description: "Для использования живых событий и настройки ваших цифровых и гибридных событий с нашим программным обеспечением вам необходимо использовать пакет сообщества.",
liveEvent_PremiumFeature_button_text: "Купить пакет сообщества",
liveEvent_setup_title: "Настройка мероприятия",
liveEvent_setup_undertitle: "Заполните все обязательные поля",
liveEvent_setup_customize_title: "Настройте ваше живое мероприятие",
liveEvent_setup_video_title: "Добавьте ресурсы к вашему мероприятию",
category_setup_title: "Настройка категории",
category_setup_undertitle: "Заполните все обязательные поля",
category_setup_customize_title: "Назовите вашу категорию",
user_setup_title: "Настройка пользователя",
user_setup_undertitle: "Заполните все обязательные поля",
user_setup_customize_title: "Настройте пользователя",
course_unpublish_banner: "Этот курс не опубликован. Он не будет виден пользователям.",
post_unpublish_banner: "Этот пост не опубликован. Он не будет виден пользователям.",
liveEvent_unpublish_banner: "Это событие не опубликовано. Оно не будет видно пользователям.",
category_unpublish_banner: "Эта категория не опубликована. Она не будет видна пользователям.",
chapter_unpublish_banner: "Эта глава не опубликована. Она не будет видна пользователям.",
analytics_total_revenue_label: "Общий доход",
analytics_total_sales_label: "Общие продажи",
};
