export const Russian: Record<string, string> = {
  documents: "документы",
  document_hub: "документ хаб",
  type: "тип",
  name: "имя",
  created_at: "создано в",
  administration: "администрация",
  create: "создать",
  create_file: "создать файл",
  create_folder: "создать папку",
  create_a_folder: "создать папку",
  public: "общественный",
  cancel: "отменить",
  placeholder: "Пожалуйста, введите имя папки",
  placeholder_file: "Пожалуйста, введите имя файла",
  edit: "редактировать",
  file: "файл",
  upload_file: "загрузить файл",
  update: "обновить",
  save: "сохранить",
  rename: "переименовать",
  are_you_sure_you_want_to_delete: "Вы уверены, что хотите удалить",
  delete: "удалить",
  a_file: "файл",
  a_folder: "папка",
  add: "добавить",
};
