export const Russian: Record<string, string> = {
  documents: "документы",
  document_hub: "документ хаб",
  type: "тип",
  name: "имя",
  created_at: "создано в",
  administration: "администрация",
  create: "создать",
  create_file: "создать файл",
  create_folder: "создать папку",
  create_a_folder: "создать папку",
  public: "общественный",
  cancel: "отменить",
  placeholder: "Пожалуйста, введите имя папки",
  placeholder_file: "Пожалуйста, введите имя файла",
  edit: "редактировать",
  file: "файл",
  upload_file: "загрузить файл",
  update: "обновить",
  save: "сохранить",
  rename: "переименовать",
  are_you_sure_you_want_to_delete: "Вы уверены, что хотите удалить",
  delete: "удалить",
  a_file: "файл",
  a_folder: "папка",
  add: "добавить",
  navigation_administration_button_text: "Администрирование",
  navigation_administration_button_text_exit: "Выход",
  navigation_theme_toggle_light: "Свет",
  navigation_theme_toggle_dark: "Темный",
  navigation_theme_toggle_system: "Система",
  navigation_language_toggle_english: "Английский",
  navigation_language_toggle_german: "Немецкий",
  navigation_language_toggle_french: "Французский",
  navigation_language_toggle_spanish: "Испанский",
  navigation_language_toggle_italian: "Итальянский",
  navigation_language_toggle_portuguese: "Португальский",
  navigation_language_toggle_russian: "Русский",
  navigation_language_toggle_mandarin: "Мандарин",
  navigation_search_placeholder: "Поиск",
  navigation_footer_text: "При поддержке",
  navigation_footer_text_product: "Продукт",
  search_courseCounter_currentCourses: "Существующие курсы",
  news_no_posts_found: "Сообщений не найдено",
  news_comments_button_label: "Комментарии",
  news_comments_input_placeholder: "Введите комментарий...",
  news_comments_showmore_label: "Показать больше +",
  news_comments_reply_button_label: "Ответить",
  live_event_futureAndPast_button_text_future: "Будущие события",
  live_event_futureAndPast_button_text_past: "Прошлые события",
  live_event_filter_button_text: "Фильтр",
  live_event_filter_title: "Фильтр живых событий",
  live_event_filter_description: "Вы можете фильтровать события, указав дату начала и/или окончания события.",
};
