version: "3.8"
services:
  hmt_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'lms_api'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lms_api'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lms_api'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lms_api'
    ports:
      # <Port exposed> 6801 : <MySQL Port running inside container> 3306
      - '6802:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
